#include("code_new.jl")
#using Plotly

#@everywhere begin
# Economies with higher development (beta and theta)
#Pre - trade liberalization
Developed_parameter = deepcopy(Baseline_parameter);
prices_initial_dev = [  0.24190237714043653
0.38077781106180153
0.2248600604939829
2.274816020027389
1.2945582363748034
0.05653056683161781
0.049450671591694605];
Developed_parameter.β[1] = 0.948;
Developed_parameter.θ[1] = 0.86;
τ_closed_trade = 0.525; #Final bilateral low tariff state
Developed_parameter.τ = τ_closed_trade * [1.0,1.0];

(residual_initial_dev,a_prime_fine_initial_dev,future_occupation_fine_initial_dev,cons_fine_initial_dev,rev_d_fine_store_initial_dev,
rev_dx_fine_store_initial_dev,rev_xx_fine_store_initial_dev,coeff_final_initial_dev,k_x_fine_initial_dev,k_d_fine_initial_dev,
l_x_fine_initial_dev,l_d_fine_initial_dev,current_distr_store_initial_dev,distr_current_initial_dev,exitflag_initial_dev,domestic_prod_initial_dev,exporter_pop_initial_dev,
domestic_pop_initial_dev,worker_pop_initial_dev,entry_share_to_domestic_initial_dev,exit_share_to_domestic_initial_dev,
entry_share_to_exporter_initial_dev,exit_share_to_worker_initial_dev,total_entry_cost_initial_dev,
total_incumbents_cost_initial_dev,total_exit_cost_initial_dev,labor_excess_demand_initial_dev,labor_demand_initial_dev,
total_consumption_initial_dev,capital_demand_initial_dev,capital_next_initial_dev,
total_demand_final_good_initial_dev,excess_demand_final_good_initial_dev,GDP_initial_dev,nomGDP_initial_dev,PPI_initial_dev,TFP_initial_dev,
TFP_within_initial_dev,TFP_across_initial_dev,TFP_second_best_initial_dev,TOT_initial_dev,TFP_d_initial_dev,
TFP_d_efficient_initial_dev,TFP_x_initial_dev,TFP_x_efficient_initial_dev,total_production_initial_dev,
domestic_price_sum_initial_dev,export_value_initial_dev,investment_initial_dev,
L_x_initial_dev,L_d_initial_dev,K_x_initial_dev,K_d_initial_dev,x_k_initial_dev,x_l_initial_dev,D_d_initial_dev,D_x_initial_dev,D_d_denom_initial_dev,D_x_denom_initial_dev,
D_d_eff_initial_dev,D_x_eff_initial_dev,D_d_denom_eff_initial_dev,D_x_denom_eff_initial_dev,K_d_ratio_initial_dev,K_x_ratio_initial_dev,
L_d_ratio_initial_dev,L_x_ratio_initial_dev,K_x_ratio_eff_initial_dev,K_d_ratio_eff_initial_dev,L_d_ratio_eff_initial_dev,
L_x_ratio_eff_initial_dev,nomGDP_d_initial_dev,nomGDP_xd_initial_dev,nomGDP_xx_initial_dev,RGDP_d_initial_dev,RGDP_xd_initial_dev,RGDP_xx_initial_dev,RGDP_initial_dev,
mean_MRPK_d_initial_dev,mean_MRPK_x_initial_dev,sd_MRPK_d_initial_dev,sd_MRPK_x_initial_dev,mean_MRPK_initial_dev,sd_MRPK_initial_dev,
mean_MRPL_d_initial_dev,mean_MRPL_x_initial_dev,sd_MRPL_d_initial_dev,sd_MRPL_x_initial_dev,mean_MRPL_initial_dev,sd_MRPL_initial_dev,
cov_TFPR_z_d_initial_dev,cov_TFPR_z_x_initial_dev,cov_TFPR_z_initial_dev,corr_TFPR_z_d_initial_dev,corr_TFPR_z_x_initial_dev,
corr_TFPR_z_initial_dev,mean_logProd_d_initial_dev,mean_logProd_x_initial_dev,mean_logProd_initial_dev,sd_logProd_d_initial_dev,
sd_logProd_x_initial_dev,sd_logProd_initial_dev,import_share_initial_dev,worker_bond_holding_initial_dev,
domestic_bond_holding_initial_dev,exporter_bond_holding_initial_dev,domestic_firm_debt_initial_dev,
exporter_firm_debt_initial_dev,avg_Pi_x_initial_dev,avg_Pi_d_initial_dev,Profit_fine_x_initial_dev,
Profit_fine_d_initial_dev,mean_cons_initial_dev,sd_cons_initial_dev,mean_income_initial_dev,sd_income_initial_dev,mean_wealth_initial_dev,
sd_wealth_initial_dev,wealth_of_workers_initial_dev,wealth_of_domestic_initial_dev,wealth_of_exporters_initial_dev,
income_of_workers_initial_dev,income_of_domestic_initial_dev,income_of_exporters_initial_dev,
cons_of_workers_initial_dev,cons_of_domestic_initial_dev,cons_of_exporters_initial_dev,GINI_wealth_initial_dev,
GINI_income_initial_dev,GINI_cons_initial_dev,p10_wealth_initial_dev,p50_wealth_initial_dev,p90_wealth_initial_dev,p99_wealth_initial_dev,p10_income_initial_dev,p50_income_initial_dev,p90_income_initial_dev,
p99_income_initial_dev,p10_cons_initial_dev,p50_cons_initial_dev,p90_cons_initial_dev,p99_cons_initial_dev,Aggr_bank_cost_initial_dev,mean_leverage_d_initial_dev,mean_leverage_x_initial_dev,mean_leverage_initial_dev,
sd_leverage_d_initial_dev,sd_leverage_x_initial_dev,sd_leverage_initial_dev,corr_MRPK_lev_d_initial_dev,corr_MRPK_lev_x_initial_dev,corr_MRPK_lev_initial_dev,exit_domestic_to_work_sum_initial_dev,
exit_exporting_to_work_sum_initial_dev,mean_growth_rev_initial_dev,sd_growth_rev_initial_dev,mean_growth_k_initial_dev,sd_growth_k_initial_dev,autocorr_rev_initial_dev,
making_losses_exporter_initial_dev,Misallocation_within_d_initial_dev,Misallocation_within_x_initial_dev,k_opt_d_fine_initial_dev,k_opt_x_fine_initial_dev,V_saved_fine_initial_dev,avg_rev_xx_entrants_initial_dev,NFA_initial_dev) = Residual_stst_detailed(prices_initial_dev, Developed_parameter);


#Closed capital markets and after trade liberalization
closed_CM_open_trade_dev_parameter = copy(Developed_parameter);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_dev_parameter.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade_dev = prices_closed_CM_open_trade_dev = [    0.2490842781272958,
 0.3799239726656807,
 0.23192180425628187,
 2.16046684198267,
 1.2704952921209134,
 0.05638316639491758,
 0.0512674722023119];

(residual_closed_CM_open_trade_dev,a_prime_fine_closed_CM_open_trade_dev,future_occupation_fine_closed_CM_open_trade_dev,cons_fine_closed_CM_open_trade_dev,rev_d_fine_store_closed_CM_open_trade_dev,
rev_dx_fine_store_closed_CM_open_trade_dev,rev_xx_fine_store_closed_CM_open_trade_dev,coeff_final_closed_CM_open_trade_dev,k_x_fine_closed_CM_open_trade_dev,k_d_fine_closed_CM_open_trade_dev,
l_x_fine_closed_CM_open_trade_dev,l_d_fine_closed_CM_open_trade_dev,current_distr_store_closed_CM_open_trade_dev,distr_current_closed_CM_open_trade_dev,exitflag_closed_CM_open_trade_dev,domestic_prod_closed_CM_open_trade_dev,exporter_pop_closed_CM_open_trade_dev,
domestic_pop_closed_CM_open_trade_dev,worker_pop_closed_CM_open_trade_dev,entry_share_to_domestic_closed_CM_open_trade_dev,exit_share_to_domestic_closed_CM_open_trade_dev,
entry_share_to_exporter_closed_CM_open_trade_dev,exit_share_to_worker_closed_CM_open_trade_dev,total_entry_cost_closed_CM_open_trade_dev,
total_incumbents_cost_closed_CM_open_trade_dev,total_exit_cost_closed_CM_open_trade_dev,labor_excess_demand_closed_CM_open_trade_dev,labor_demand_closed_CM_open_trade_dev,
total_consumption_closed_CM_open_trade_dev,capital_demand_closed_CM_open_trade_dev,capital_next_closed_CM_open_trade_dev,
total_demand_final_good_closed_CM_open_trade_dev,excess_demand_final_good_closed_CM_open_trade_dev,GDP_closed_CM_open_trade_dev,nomGDP_closed_CM_open_trade_dev,PPI_closed_CM_open_trade_dev,TFP_closed_CM_open_trade_dev,
TFP_within_closed_CM_open_trade_dev,TFP_across_closed_CM_open_trade_dev,TFP_second_best_closed_CM_open_trade_dev,TOT_closed_CM_open_trade_dev,TFP_d_closed_CM_open_trade_dev,
TFP_d_efficient_closed_CM_open_trade_dev,TFP_x_closed_CM_open_trade_dev,TFP_x_efficient_closed_CM_open_trade_dev,total_production_closed_CM_open_trade_dev,
domestic_price_sum_closed_CM_open_trade_dev,export_value_closed_CM_open_trade_dev,investment_closed_CM_open_trade_dev,
L_x_closed_CM_open_trade_dev,L_d_closed_CM_open_trade_dev,K_x_closed_CM_open_trade_dev,K_d_closed_CM_open_trade_dev,x_k_closed_CM_open_trade_dev,x_l_closed_CM_open_trade_dev,D_d_closed_CM_open_trade_dev,D_x_closed_CM_open_trade_dev,D_d_denom_closed_CM_open_trade_dev,D_x_denom_closed_CM_open_trade_dev,
D_d_eff_closed_CM_open_trade_dev,D_x_eff_closed_CM_open_trade_dev,D_d_denom_eff_closed_CM_open_trade_dev,D_x_denom_eff_closed_CM_open_trade_dev,K_d_ratio_closed_CM_open_trade_dev,K_x_ratio_closed_CM_open_trade_dev,
L_d_ratio_closed_CM_open_trade_dev,L_x_ratio_closed_CM_open_trade_dev,K_x_ratio_eff_closed_CM_open_trade_dev,K_d_ratio_eff_closed_CM_open_trade_dev,L_d_ratio_eff_closed_CM_open_trade_dev,
L_x_ratio_eff_closed_CM_open_trade_dev,nomGDP_d_closed_CM_open_trade_dev,nomGDP_xd_closed_CM_open_trade_dev,nomGDP_xx_closed_CM_open_trade_dev,RGDP_d_closed_CM_open_trade_dev,RGDP_xd_closed_CM_open_trade_dev,RGDP_xx_closed_CM_open_trade_dev,RGDP_closed_CM_open_trade_dev,
mean_MRPK_d_closed_CM_open_trade_dev,mean_MRPK_x_closed_CM_open_trade_dev,sd_MRPK_d_closed_CM_open_trade_dev,sd_MRPK_x_closed_CM_open_trade_dev,mean_MRPK_closed_CM_open_trade_dev,sd_MRPK_closed_CM_open_trade_dev,
mean_MRPL_d_closed_CM_open_trade_dev,mean_MRPL_x_closed_CM_open_trade_dev,sd_MRPL_d_closed_CM_open_trade_dev,sd_MRPL_x_closed_CM_open_trade_dev,mean_MRPL_closed_CM_open_trade_dev,sd_MRPL_closed_CM_open_trade_dev,
cov_TFPR_z_d_closed_CM_open_trade_dev,cov_TFPR_z_x_closed_CM_open_trade_dev,cov_TFPR_z_closed_CM_open_trade_dev,corr_TFPR_z_d_closed_CM_open_trade_dev,corr_TFPR_z_x_closed_CM_open_trade_dev,
corr_TFPR_z_closed_CM_open_trade_dev,mean_logProd_d_closed_CM_open_trade_dev,mean_logProd_x_closed_CM_open_trade_dev,mean_logProd_closed_CM_open_trade_dev,sd_logProd_d_closed_CM_open_trade_dev,
sd_logProd_x_closed_CM_open_trade_dev,sd_logProd_closed_CM_open_trade_dev,import_share_closed_CM_open_trade_dev,worker_bond_holding_closed_CM_open_trade_dev,
domestic_bond_holding_closed_CM_open_trade_dev,exporter_bond_holding_closed_CM_open_trade_dev,domestic_firm_debt_closed_CM_open_trade_dev,
exporter_firm_debt_closed_CM_open_trade_dev,avg_Pi_x_closed_CM_open_trade_dev,avg_Pi_d_closed_CM_open_trade_dev,Profit_fine_x_closed_CM_open_trade_dev,
Profit_fine_d_closed_CM_open_trade_dev,mean_cons_closed_CM_open_trade_dev,sd_cons_closed_CM_open_trade_dev,mean_income_closed_CM_open_trade_dev,sd_income_closed_CM_open_trade_dev,mean_wealth_closed_CM_open_trade_dev,
sd_wealth_closed_CM_open_trade_dev,wealth_of_workers_closed_CM_open_trade_dev,wealth_of_domestic_closed_CM_open_trade_dev,wealth_of_exporters_closed_CM_open_trade_dev,
income_of_workers_closed_CM_open_trade_dev,income_of_domestic_closed_CM_open_trade_dev,income_of_exporters_closed_CM_open_trade_dev,
cons_of_workers_closed_CM_open_trade_dev,cons_of_domestic_closed_CM_open_trade_dev,cons_of_exporters_closed_CM_open_trade_dev,GINI_wealth_closed_CM_open_trade_dev,
GINI_income_closed_CM_open_trade_dev,GINI_cons_closed_CM_open_trade_dev,p10_wealth_closed_CM_open_trade_dev,p50_wealth_closed_CM_open_trade_dev,p90_wealth_closed_CM_open_trade_dev,p99_wealth_closed_CM_open_trade_dev,p10_income_closed_CM_open_trade_dev,p50_income_closed_CM_open_trade_dev,p90_income_closed_CM_open_trade_dev,
p99_income_closed_CM_open_trade_dev,p10_cons_closed_CM_open_trade_dev,p50_cons_closed_CM_open_trade_dev,p90_cons_closed_CM_open_trade_dev,p99_cons_closed_CM_open_trade_dev,Aggr_bank_cost_closed_CM_open_trade_dev,mean_leverage_d_closed_CM_open_trade_dev,mean_leverage_x_closed_CM_open_trade_dev,mean_leverage_closed_CM_open_trade_dev,
sd_leverage_d_closed_CM_open_trade_dev,sd_leverage_x_closed_CM_open_trade_dev,sd_leverage_closed_CM_open_trade_dev,corr_MRPK_lev_d_closed_CM_open_trade_dev,corr_MRPK_lev_x_closed_CM_open_trade_dev,corr_MRPK_lev_closed_CM_open_trade_dev,exit_domestic_to_work_sum_closed_CM_open_trade_dev,
exit_exporting_to_work_sum_closed_CM_open_trade_dev,mean_growth_rev_closed_CM_open_trade_dev,sd_growth_rev_closed_CM_open_trade_dev,mean_growth_k_closed_CM_open_trade_dev,sd_growth_k_closed_CM_open_trade_dev,autocorr_rev_closed_CM_open_trade_dev,making_losses_exporter_closed_CM_open_trade_dev,
Misallocation_within_d_closed_CM_open_trade_dev,Misallocation_within_x_closed_CM_open_trade_dev,k_opt_d_fine_closed_CM_open_trade_dev,k_opt_x_fine_closed_CM_open_trade_dev,V_saved_fine_closed_CM_open_trade_dev,avg_rev_xx_entrants_closed_CM_open_trade_dev,NFA_closed_CM_open_trade_dev) = Residual_stst_detailed(prices_closed_CM_open_trade_dev, closed_CM_open_trade_dev_parameter);

#Open capital markets and after trade liberalization
open_CM_open_trade_dev_parameter = copy(Developed_parameter);
open_CM_open_trade_dev_parameter.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_dev_parameter.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade_dev =  [   0.23573296929207438
0.37841436994004274
0.22266004304596554
2.1624372570175616
1.239666741111687
0.050576716043028935];

(residual_open_CM_open_trade_dev,a_prime_fine_open_CM_open_trade_dev,future_occupation_fine_open_CM_open_trade_dev,cons_fine_open_CM_open_trade_dev,rev_d_fine_store_open_CM_open_trade_dev,
rev_dx_fine_store_open_CM_open_trade_dev,rev_xx_fine_store_open_CM_open_trade_dev,coeff_final_open_CM_open_trade_dev,k_x_fine_open_CM_open_trade_dev,k_d_fine_open_CM_open_trade_dev,
l_x_fine_open_CM_open_trade_dev,l_d_fine_open_CM_open_trade_dev,current_distr_store_open_CM_open_trade_dev,distr_current_open_CM_open_trade_dev,exitflag_open_CM_open_trade_dev,domestic_prod_open_CM_open_trade_dev,exporter_pop_open_CM_open_trade_dev,
domestic_pop_open_CM_open_trade_dev,worker_pop_open_CM_open_trade_dev,entry_share_to_domestic_open_CM_open_trade_dev,exit_share_to_domestic_open_CM_open_trade_dev,
entry_share_to_exporter_open_CM_open_trade_dev,exit_share_to_worker_open_CM_open_trade_dev,total_entry_cost_open_CM_open_trade_dev,
total_incumbents_cost_open_CM_open_trade_dev,total_exit_cost_open_CM_open_trade_dev,labor_excess_demand_open_CM_open_trade_dev,labor_demand_open_CM_open_trade_dev,
total_consumption_open_CM_open_trade_dev,capital_demand_open_CM_open_trade_dev,capital_next_open_CM_open_trade_dev,
total_demand_final_good_open_CM_open_trade_dev,excess_demand_final_good_open_CM_open_trade_dev,GDP_open_CM_open_trade_dev,nomGDP_open_CM_open_trade_dev,PPI_open_CM_open_trade_dev,TFP_open_CM_open_trade_dev,
TFP_within_open_CM_open_trade_dev,TFP_across_open_CM_open_trade_dev,TFP_second_best_open_CM_open_trade_dev,TOT_open_CM_open_trade_dev,TFP_d_open_CM_open_trade_dev,
TFP_d_efficient_open_CM_open_trade_dev,TFP_x_open_CM_open_trade_dev,TFP_x_efficient_open_CM_open_trade_dev,total_production_open_CM_open_trade_dev,
domestic_price_sum_open_CM_open_trade_dev,export_value_open_CM_open_trade_dev,investment_open_CM_open_trade_dev,
L_x_open_CM_open_trade_dev,L_d_open_CM_open_trade_dev,K_x_open_CM_open_trade_dev,K_d_open_CM_open_trade_dev,x_k_open_CM_open_trade_dev,x_l_open_CM_open_trade_dev,D_d_open_CM_open_trade_dev,D_x_open_CM_open_trade_dev,D_d_denom_open_CM_open_trade_dev,D_x_denom_open_CM_open_trade_dev,
D_d_eff_open_CM_open_trade_dev,D_x_eff_open_CM_open_trade_dev,D_d_denom_eff_open_CM_open_trade_dev,D_x_denom_eff_open_CM_open_trade_dev,K_d_ratio_open_CM_open_trade_dev,K_x_ratio_open_CM_open_trade_dev,
L_d_ratio_open_CM_open_trade_dev,L_x_ratio_open_CM_open_trade_dev,K_x_ratio_eff_open_CM_open_trade_dev,K_d_ratio_eff_open_CM_open_trade_dev,L_d_ratio_eff_open_CM_open_trade_dev,
L_x_ratio_eff_open_CM_open_trade_dev,nomGDP_d_open_CM_open_trade_dev,nomGDP_xd_open_CM_open_trade_dev,nomGDP_xx_open_CM_open_trade_dev,RGDP_d_open_CM_open_trade_dev,RGDP_xd_open_CM_open_trade_dev,RGDP_xx_open_CM_open_trade_dev,RGDP_open_CM_open_trade_dev,
mean_MRPK_d_open_CM_open_trade_dev,mean_MRPK_x_open_CM_open_trade_dev,sd_MRPK_d_open_CM_open_trade_dev,sd_MRPK_x_open_CM_open_trade_dev,mean_MRPK_open_CM_open_trade_dev,sd_MRPK_open_CM_open_trade_dev,
mean_MRPL_d_open_CM_open_trade_dev,mean_MRPL_x_open_CM_open_trade_dev,sd_MRPL_d_open_CM_open_trade_dev,sd_MRPL_x_open_CM_open_trade_dev,mean_MRPL_open_CM_open_trade_dev,sd_MRPL_open_CM_open_trade_dev,
cov_TFPR_z_d_open_CM_open_trade_dev,cov_TFPR_z_x_open_CM_open_trade_dev,cov_TFPR_z_open_CM_open_trade_dev,corr_TFPR_z_d_open_CM_open_trade_dev,corr_TFPR_z_x_open_CM_open_trade_dev,
corr_TFPR_z_open_CM_open_trade_dev,mean_logProd_d_open_CM_open_trade_dev,mean_logProd_x_open_CM_open_trade_dev,mean_logProd_open_CM_open_trade_dev,sd_logProd_d_open_CM_open_trade_dev,
sd_logProd_x_open_CM_open_trade_dev,sd_logProd_open_CM_open_trade_dev,import_share_open_CM_open_trade_dev,worker_bond_holding_open_CM_open_trade_dev,
domestic_bond_holding_open_CM_open_trade_dev,exporter_bond_holding_open_CM_open_trade_dev,domestic_firm_debt_open_CM_open_trade_dev,
exporter_firm_debt_open_CM_open_trade_dev,avg_Pi_x_open_CM_open_trade_dev,avg_Pi_d_open_CM_open_trade_dev,Profit_fine_x_open_CM_open_trade_dev,
Profit_fine_d_open_CM_open_trade_dev,mean_cons_open_CM_open_trade_dev,sd_cons_open_CM_open_trade_dev,mean_income_open_CM_open_trade_dev,sd_income_open_CM_open_trade_dev,mean_wealth_open_CM_open_trade_dev,
sd_wealth_open_CM_open_trade_dev,wealth_of_workers_open_CM_open_trade_dev,wealth_of_domestic_open_CM_open_trade_dev,wealth_of_exporters_open_CM_open_trade_dev,
income_of_workers_open_CM_open_trade_dev,income_of_domestic_open_CM_open_trade_dev,income_of_exporters_open_CM_open_trade_dev,
cons_of_workers_open_CM_open_trade_dev,cons_of_domestic_open_CM_open_trade_dev,cons_of_exporters_open_CM_open_trade_dev,GINI_wealth_open_CM_open_trade_dev,
GINI_income_open_CM_open_trade_dev,GINI_cons_open_CM_open_trade_dev,p10_wealth_open_CM_open_trade_dev,p50_wealth_open_CM_open_trade_dev,p90_wealth_open_CM_open_trade_dev,p99_wealth_open_CM_open_trade_dev,p10_income_open_CM_open_trade_dev,p50_income_open_CM_open_trade_dev,p90_income_open_CM_open_trade_dev,
p99_income_open_CM_open_trade_dev,p10_cons_open_CM_open_trade_dev,p50_cons_open_CM_open_trade_dev,p90_cons_open_CM_open_trade_dev,p99_cons_open_CM_open_trade_dev,Aggr_bank_cost_open_CM_open_trade_dev,mean_leverage_d_open_CM_open_trade_dev,mean_leverage_x_open_CM_open_trade_dev,mean_leverage_open_CM_open_trade_dev,
sd_leverage_d_open_CM_open_trade_dev,sd_leverage_x_open_CM_open_trade_dev,sd_leverage_open_CM_open_trade_dev,corr_MRPK_lev_d_open_CM_open_trade_dev,corr_MRPK_lev_x_open_CM_open_trade_dev,corr_MRPK_lev_open_CM_open_trade_dev,exit_domestic_to_work_sum_open_CM_open_trade_dev,
exit_exporting_to_work_sum_open_CM_open_trade_dev,mean_growth_rev_open_CM_open_trade_dev,sd_growth_rev_open_CM_open_trade_dev,mean_growth_k_open_CM_open_trade_dev,sd_growth_k_open_CM_open_trade_dev,autocorr_rev_open_CM_open_trade_dev,making_losses_exporter_open_CM_open_trade_dev,
Misallocation_within_d_open_CM_open_trade_dev,Misallocation_within_x_open_CM_open_trade_dev,k_opt_d_fine_open_CM_open_trade_dev,k_opt_x_fine_open_CM_open_trade_dev,V_saved_fine_open_CM_open_trade_dev,avg_rev_xx_entrants_open_CM_open_trade_dev,NFA_open_CM_open_trade_dev) = Residual_stst_detailed(prices_open_CM_open_trade_dev, open_CM_open_trade_dev_parameter);
