#include("code_new.jl")
#using Plotly
Baseline_parameter_FC = copy(Baseline_parameter);
#@everywhere begin
#Pre - trade liberalization
prices_initial_FC = [  0.15489113455876022
0.3769431820310825
0.15807849544856725
2.2242782493713995
1.3905640153753875
0.1084391488714271
0.04912869462349367];

τ_closed_trade = 0.525; #Final bilateral low tariff state
Baseline_parameter_FC.τ = τ_closed_trade * [1.0,1.0];
Baseline_parameter_FC.Fₓ[1] = 0;
Baseline_parameter_FC.FMₓ[1] = 1.5

(residual_initial_FC,a_prime_fine_initial_FC,future_occupation_fine_initial_FC,cons_fine_initial_FC,rev_d_fine_store_initial_FC,
rev_dx_fine_store_initial_FC,rev_xx_fine_store_initial_FC,coeff_final_initial_FC,k_x_fine_initial_FC,k_d_fine_initial_FC,
l_x_fine_initial_FC,l_d_fine_initial_FC,current_distr_store_initial_FC,distr_current_initial_FC,exitflag_initial_FC,domestic_prod_initial_FC,exporter_pop_initial_FC,
domestic_pop_initial_FC,worker_pop_initial_FC,entry_share_to_domestic_initial_FC,exit_share_to_domestic_initial_FC,
entry_share_to_exporter_initial_FC,exit_share_to_worker_initial_FC,total_entry_cost_initial_FC,
total_incumbents_cost_initial_FC,total_exit_cost_initial_FC,labor_excess_demand_initial_FC,labor_demand_initial_FC,
total_consumption_initial_FC,capital_demand_initial_FC,capital_next_initial_FC,
total_demand_final_good_initial_FC,excess_demand_final_good_initial_FC,GDP_initial_FC,nomGDP_initial_FC,PPI_initial_FC,TFP_initial_FC,
TFP_within_initial_FC,TFP_across_initial_FC,TFP_second_best_initial_FC,TOT_initial_FC,TFP_d_initial_FC,
TFP_d_efficient_initial_FC,TFP_x_initial_FC,TFP_x_efficient_initial_FC,total_production_initial_FC,
domestic_price_sum_initial_FC,export_value_initial_FC,investment_initial_FC,
L_x_initial_FC,L_d_initial_FC,K_x_initial_FC,K_d_initial_FC,x_k_initial_FC,x_l_initial_FC,D_d_initial_FC,D_x_initial_FC,D_d_denom_initial_FC,D_x_denom_initial_FC,
D_d_eff_initial_FC,D_x_eff_initial_FC,D_d_denom_eff_initial_FC,D_x_denom_eff_initial_FC,K_d_ratio_initial_FC,K_x_ratio_initial_FC,
L_d_ratio_initial_FC,L_x_ratio_initial_FC,K_x_ratio_eff_initial_FC,K_d_ratio_eff_initial_FC,L_d_ratio_eff_initial_FC,
L_x_ratio_eff_initial_FC,nomGDP_d_initial_FC,nomGDP_xd_initial_FC,nomGDP_xx_initial_FC,RGDP_d_initial_FC,RGDP_xd_initial_FC,RGDP_xx_initial_FC,RGDP_initial_FC,
mean_MRPK_d_initial_FC,mean_MRPK_x_initial_FC,sd_MRPK_d_initial_FC,sd_MRPK_x_initial_FC,mean_MRPK_initial_FC,sd_MRPK_initial_FC,
mean_MRPL_d_initial_FC,mean_MRPL_x_initial_FC,sd_MRPL_d_initial_FC,sd_MRPL_x_initial_FC,mean_MRPL_initial_FC,sd_MRPL_initial_FC,
cov_TFPR_z_d_initial_FC,cov_TFPR_z_x_initial_FC,cov_TFPR_z_initial_FC,corr_TFPR_z_d_initial_FC,corr_TFPR_z_x_initial_FC,
corr_TFPR_z_initial_FC,mean_logProd_d_initial_FC,mean_logProd_x_initial_FC,mean_logProd_initial_FC,sd_logProd_d_initial_FC,
sd_logProd_x_initial_FC,sd_logProd_initial_FC,import_share_initial_FC,worker_bond_holding_initial_FC,
domestic_bond_holding_initial_FC,exporter_bond_holding_initial_FC,domestic_firm_debt_initial_FC,
exporter_firm_debt_initial_FC,avg_Pi_x_initial_FC,avg_Pi_d_initial_FC,Profit_fine_x_initial_FC,
Profit_fine_d_initial_FC,mean_cons_initial_FC,sd_cons_initial_FC,mean_income_initial_FC,sd_income_initial_FC,mean_wealth_initial_FC,
sd_wealth_initial_FC,wealth_of_workers_initial_FC,wealth_of_domestic_initial_FC,wealth_of_exporters_initial_FC,
income_of_workers_initial_FC,income_of_domestic_initial_FC,income_of_exporters_initial_FC,
cons_of_workers_initial_FC,cons_of_domestic_initial_FC,cons_of_exporters_initial_FC,GINI_wealth_initial_FC,
GINI_income_initial_FC,GINI_cons_initial_FC,p10_wealth_initial_FC,p50_wealth_initial_FC,p90_wealth_initial_FC,p99_wealth_initial_FC,p10_income_initial_FC,p50_income_initial_FC,p90_income_initial_FC,
p99_income_initial_FC,p10_cons_initial_FC,p50_cons_initial_FC,p90_cons_initial_FC,p99_cons_initial_FC,Aggr_bank_cost_initial_FC,mean_leverage_d_initial_FC,mean_leverage_x_initial_FC,mean_leverage_initial_FC,
sd_leverage_d_initial_FC,sd_leverage_x_initial_FC,sd_leverage_initial_FC,corr_MRPK_lev_d_initial_FC,corr_MRPK_lev_x_initial_FC,corr_MRPK_lev_initial_FC,exit_domestic_to_work_sum_initial_FC,
exit_exporting_to_work_sum_initial_FC,mean_growth_rev_initial_FC,sd_growth_rev_initial_FC,mean_growth_k_initial_FC,sd_growth_k_initial_FC,autocorr_rev_initial_FC,
making_losses_exporter_initial_FC,Misallocation_within_d_initial_FC,Misallocation_within_x_initial_FC,k_opt_d_fine_initial_FC,k_opt_x_fine_initial_FC,V_saved_fine_initial_FC,avg_rev_xx_entrants_initial_FC,NFA_initial_FC) = Residual_stst_detailed(prices_initial_FC, Baseline_parameter_FC);

#Closed capital markets and after trade liberalization
closed_CM_open_trade_parameter_FC = copy(Baseline_parameter_FC);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_parameter_FC.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade_FC = [   0.16461400803956427
0.3785482477984803
0.1683929666963782
2.098346429748793
1.421423158753159
0.10929322342780848
0.051986243299611296];

(residual_closed_CM_open_trade_FC,a_prime_fine_closed_CM_open_trade_FC,future_occupation_fine_closed_CM_open_trade_FC,cons_fine_closed_CM_open_trade_FC,rev_d_fine_store_closed_CM_open_trade_FC,
rev_dx_fine_store_closed_CM_open_trade_FC,rev_xx_fine_store_closed_CM_open_trade_FC,coeff_final_closed_CM_open_trade_FC,k_x_fine_closed_CM_open_trade_FC,k_d_fine_closed_CM_open_trade_FC,
l_x_fine_closed_CM_open_trade_FC,l_d_fine_closed_CM_open_trade_FC,current_distr_store_closed_CM_open_trade_FC,distr_current_closed_CM_open_trade_FC,exitflag_closed_CM_open_trade_FC,domestic_prod_closed_CM_open_trade_FC,exporter_pop_closed_CM_open_trade_FC,
domestic_pop_closed_CM_open_trade_FC,worker_pop_closed_CM_open_trade_FC,entry_share_to_domestic_closed_CM_open_trade_FC,exit_share_to_domestic_closed_CM_open_trade_FC,
entry_share_to_exporter_closed_CM_open_trade_FC,exit_share_to_worker_closed_CM_open_trade_FC,total_entry_cost_closed_CM_open_trade_FC,
total_incumbents_cost_closed_CM_open_trade_FC,total_exit_cost_closed_CM_open_trade_FC,labor_excess_demand_closed_CM_open_trade_FC,labor_demand_closed_CM_open_trade_FC,
total_consumption_closed_CM_open_trade_FC,capital_demand_closed_CM_open_trade_FC,capital_next_closed_CM_open_trade_FC,
total_demand_final_good_closed_CM_open_trade_FC,excess_demand_final_good_closed_CM_open_trade_FC,GDP_closed_CM_open_trade_FC,nomGDP_closed_CM_open_trade_FC,PPI_closed_CM_open_trade_FC,TFP_closed_CM_open_trade_FC,
TFP_within_closed_CM_open_trade_FC,TFP_across_closed_CM_open_trade_FC,TFP_second_best_closed_CM_open_trade_FC,TOT_closed_CM_open_trade_FC,TFP_d_closed_CM_open_trade_FC,
TFP_d_efficient_closed_CM_open_trade_FC,TFP_x_closed_CM_open_trade_FC,TFP_x_efficient_closed_CM_open_trade_FC,total_production_closed_CM_open_trade_FC,
domestic_price_sum_closed_CM_open_trade_FC,export_value_closed_CM_open_trade_FC,investment_closed_CM_open_trade_FC,
L_x_closed_CM_open_trade_FC,L_d_closed_CM_open_trade_FC,K_x_closed_CM_open_trade_FC,K_d_closed_CM_open_trade_FC,x_k_closed_CM_open_trade_FC,x_l_closed_CM_open_trade_FC,D_d_closed_CM_open_trade_FC,D_x_closed_CM_open_trade_FC,D_d_denom_closed_CM_open_trade_FC,D_x_denom_closed_CM_open_trade_FC,
D_d_eff_closed_CM_open_trade_FC,D_x_eff_closed_CM_open_trade_FC,D_d_denom_eff_closed_CM_open_trade_FC,D_x_denom_eff_closed_CM_open_trade_FC,K_d_ratio_closed_CM_open_trade_FC,K_x_ratio_closed_CM_open_trade_FC,
L_d_ratio_closed_CM_open_trade_FC,L_x_ratio_closed_CM_open_trade_FC,K_x_ratio_eff_closed_CM_open_trade_FC,K_d_ratio_eff_closed_CM_open_trade_FC,L_d_ratio_eff_closed_CM_open_trade_FC,
L_x_ratio_eff_closed_CM_open_trade_FC,nomGDP_d_closed_CM_open_trade_FC,nomGDP_xd_closed_CM_open_trade_FC,nomGDP_xx_closed_CM_open_trade_FC,RGDP_d_closed_CM_open_trade_FC,RGDP_xd_closed_CM_open_trade_FC,RGDP_xx_closed_CM_open_trade_FC,RGDP_closed_CM_open_trade_FC,
mean_MRPK_d_closed_CM_open_trade_FC,mean_MRPK_x_closed_CM_open_trade_FC,sd_MRPK_d_closed_CM_open_trade_FC,sd_MRPK_x_closed_CM_open_trade_FC,mean_MRPK_closed_CM_open_trade_FC,sd_MRPK_closed_CM_open_trade_FC,
mean_MRPL_d_closed_CM_open_trade_FC,mean_MRPL_x_closed_CM_open_trade_FC,sd_MRPL_d_closed_CM_open_trade_FC,sd_MRPL_x_closed_CM_open_trade_FC,mean_MRPL_closed_CM_open_trade_FC,sd_MRPL_closed_CM_open_trade_FC,
cov_TFPR_z_d_closed_CM_open_trade_FC,cov_TFPR_z_x_closed_CM_open_trade_FC,cov_TFPR_z_closed_CM_open_trade_FC,corr_TFPR_z_d_closed_CM_open_trade_FC,corr_TFPR_z_x_closed_CM_open_trade_FC,
corr_TFPR_z_closed_CM_open_trade_FC,mean_logProd_d_closed_CM_open_trade_FC,mean_logProd_x_closed_CM_open_trade_FC,mean_logProd_closed_CM_open_trade_FC,sd_logProd_d_closed_CM_open_trade_FC,
sd_logProd_x_closed_CM_open_trade_FC,sd_logProd_closed_CM_open_trade_FC,import_share_closed_CM_open_trade_FC,worker_bond_holding_closed_CM_open_trade_FC,
domestic_bond_holding_closed_CM_open_trade_FC,exporter_bond_holding_closed_CM_open_trade_FC,domestic_firm_debt_closed_CM_open_trade_FC,
exporter_firm_debt_closed_CM_open_trade_FC,avg_Pi_x_closed_CM_open_trade_FC,avg_Pi_d_closed_CM_open_trade_FC,Profit_fine_x_closed_CM_open_trade_FC,
Profit_fine_d_closed_CM_open_trade_FC,mean_cons_closed_CM_open_trade_FC,sd_cons_closed_CM_open_trade_FC,mean_income_closed_CM_open_trade_FC,sd_income_closed_CM_open_trade_FC,mean_wealth_closed_CM_open_trade_FC,
sd_wealth_closed_CM_open_trade_FC,wealth_of_workers_closed_CM_open_trade_FC,wealth_of_domestic_closed_CM_open_trade_FC,wealth_of_exporters_closed_CM_open_trade_FC,
income_of_workers_closed_CM_open_trade_FC,income_of_domestic_closed_CM_open_trade_FC,income_of_exporters_closed_CM_open_trade_FC,
cons_of_workers_closed_CM_open_trade_FC,cons_of_domestic_closed_CM_open_trade_FC,cons_of_exporters_closed_CM_open_trade_FC,GINI_wealth_closed_CM_open_trade_FC,
GINI_income_closed_CM_open_trade_FC,GINI_cons_closed_CM_open_trade_FC,p10_wealth_closed_CM_open_trade_FC,p50_wealth_closed_CM_open_trade_FC,p90_wealth_closed_CM_open_trade_FC,p99_wealth_closed_CM_open_trade_FC,p10_income_closed_CM_open_trade_FC,p50_income_closed_CM_open_trade_FC,p90_income_closed_CM_open_trade_FC,
p99_income_closed_CM_open_trade_FC,p10_cons_closed_CM_open_trade_FC,p50_cons_closed_CM_open_trade_FC,p90_cons_closed_CM_open_trade_FC,p99_cons_closed_CM_open_trade_FC,Aggr_bank_cost_closed_CM_open_trade_FC,mean_leverage_d_closed_CM_open_trade_FC,mean_leverage_x_closed_CM_open_trade_FC,mean_leverage_closed_CM_open_trade_FC,
sd_leverage_d_closed_CM_open_trade_FC,sd_leverage_x_closed_CM_open_trade_FC,sd_leverage_closed_CM_open_trade_FC,corr_MRPK_lev_d_closed_CM_open_trade_FC,corr_MRPK_lev_x_closed_CM_open_trade_FC,corr_MRPK_lev_closed_CM_open_trade_FC,exit_domestic_to_work_sum_closed_CM_open_trade_FC,
exit_exporting_to_work_sum_closed_CM_open_trade_FC,mean_growth_rev_closed_CM_open_trade_FC,sd_growth_rev_closed_CM_open_trade_FC,mean_growth_k_closed_CM_open_trade_FC,sd_growth_k_closed_CM_open_trade_FC,autocorr_rev_closed_CM_open_trade_FC,making_losses_exporter_closed_CM_open_trade_FC,
Misallocation_within_d_closed_CM_open_trade_FC,Misallocation_within_x_closed_CM_open_trade_FC,k_opt_d_fine_closed_CM_open_trade_FC,k_opt_x_fine_closed_CM_open_trade_FC,V_saved_fine_closed_CM_open_trade_FC,avg_rev_xx_entrants_closed_CM_open_trade_FC,NFA_closed_CM_open_trade_FC) = Residual_stst_detailed(prices_closed_CM_open_trade_FC, closed_CM_open_trade_parameter_FC);

#Open capital markets and after trade liberalization
open_CM_open_trade_parameter_FC  = copy(Baseline_parameter_FC);
open_CM_open_trade_parameter_FC.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_parameter_FC.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade_FC =  [ 0.16151776167776194
0.3858746701434526
0.1613969727884557
2.2678857766954295
1.3795389286135011
0.05125990785668778];

(residual_open_CM_open_trade_FC,a_prime_fine_open_CM_open_trade_FC,future_occupation_fine_open_CM_open_trade_FC,cons_fine_open_CM_open_trade_FC,rev_d_fine_store_open_CM_open_trade_FC,
rev_dx_fine_store_open_CM_open_trade_FC,rev_xx_fine_store_open_CM_open_trade_FC,coeff_final_open_CM_open_trade_FC,k_x_fine_open_CM_open_trade_FC,k_d_fine_open_CM_open_trade_FC,
l_x_fine_open_CM_open_trade_FC,l_d_fine_open_CM_open_trade_FC,current_distr_store_open_CM_open_trade_FC,distr_current_open_CM_open_trade_FC,exitflag_open_CM_open_trade_FC,domestic_prod_open_CM_open_trade_FC,exporter_pop_open_CM_open_trade_FC,
domestic_pop_open_CM_open_trade_FC,worker_pop_open_CM_open_trade_FC,entry_share_to_domestic_open_CM_open_trade_FC,exit_share_to_domestic_open_CM_open_trade_FC,
entry_share_to_exporter_open_CM_open_trade_FC,exit_share_to_worker_open_CM_open_trade_FC,total_entry_cost_open_CM_open_trade_FC,
total_incumbents_cost_open_CM_open_trade_FC,total_exit_cost_open_CM_open_trade_FC,labor_excess_demand_open_CM_open_trade_FC,labor_demand_open_CM_open_trade_FC,
total_consumption_open_CM_open_trade_FC,capital_demand_open_CM_open_trade_FC,capital_next_open_CM_open_trade_FC,
total_demand_final_good_open_CM_open_trade_FC,excess_demand_final_good_open_CM_open_trade_FC,GDP_open_CM_open_trade_FC,nomGDP_open_CM_open_trade_FC,PPI_open_CM_open_trade_FC,TFP_open_CM_open_trade_FC,
TFP_within_open_CM_open_trade_FC,TFP_across_open_CM_open_trade_FC,TFP_second_best_open_CM_open_trade_FC,TOT_open_CM_open_trade_FC,TFP_d_open_CM_open_trade_FC,
TFP_d_efficient_open_CM_open_trade_FC,TFP_x_open_CM_open_trade_FC,TFP_x_efficient_open_CM_open_trade_FC,total_production_open_CM_open_trade_FC,
domestic_price_sum_open_CM_open_trade_FC,export_value_open_CM_open_trade_FC,investment_open_CM_open_trade_FC,
L_x_open_CM_open_trade_FC,L_d_open_CM_open_trade_FC,K_x_open_CM_open_trade_FC,K_d_open_CM_open_trade_FC,x_k_open_CM_open_trade_FC,x_l_open_CM_open_trade_FC,D_d_open_CM_open_trade_FC,D_x_open_CM_open_trade_FC,D_d_denom_open_CM_open_trade_FC,D_x_denom_open_CM_open_trade_FC,
D_d_eff_open_CM_open_trade_FC,D_x_eff_open_CM_open_trade_FC,D_d_denom_eff_open_CM_open_trade_FC,D_x_denom_eff_open_CM_open_trade_FC,K_d_ratio_open_CM_open_trade_FC,K_x_ratio_open_CM_open_trade_FC,
L_d_ratio_open_CM_open_trade_FC,L_x_ratio_open_CM_open_trade_FC,K_x_ratio_eff_open_CM_open_trade_FC,K_d_ratio_eff_open_CM_open_trade_FC,L_d_ratio_eff_open_CM_open_trade_FC,
L_x_ratio_eff_open_CM_open_trade_FC,nomGDP_d_open_CM_open_trade_FC,nomGDP_xd_open_CM_open_trade_FC,nomGDP_xx_open_CM_open_trade_FC,RGDP_d_open_CM_open_trade_FC,RGDP_xd_open_CM_open_trade_FC,RGDP_xx_open_CM_open_trade_FC,RGDP_open_CM_open_trade_FC,
mean_MRPK_d_open_CM_open_trade_FC,mean_MRPK_x_open_CM_open_trade_FC,sd_MRPK_d_open_CM_open_trade_FC,sd_MRPK_x_open_CM_open_trade_FC,mean_MRPK_open_CM_open_trade_FC,sd_MRPK_open_CM_open_trade_FC,
mean_MRPL_d_open_CM_open_trade_FC,mean_MRPL_x_open_CM_open_trade_FC,sd_MRPL_d_open_CM_open_trade_FC,sd_MRPL_x_open_CM_open_trade_FC,mean_MRPL_open_CM_open_trade_FC,sd_MRPL_open_CM_open_trade_FC,
cov_TFPR_z_d_open_CM_open_trade_FC,cov_TFPR_z_x_open_CM_open_trade_FC,cov_TFPR_z_open_CM_open_trade_FC,corr_TFPR_z_d_open_CM_open_trade_FC,corr_TFPR_z_x_open_CM_open_trade_FC,
corr_TFPR_z_open_CM_open_trade_FC,mean_logProd_d_open_CM_open_trade_FC,mean_logProd_x_open_CM_open_trade_FC,mean_logProd_open_CM_open_trade_FC,sd_logProd_d_open_CM_open_trade_FC,
sd_logProd_x_open_CM_open_trade_FC,sd_logProd_open_CM_open_trade_FC,import_share_open_CM_open_trade_FC,worker_bond_holding_open_CM_open_trade_FC,
domestic_bond_holding_open_CM_open_trade_FC,exporter_bond_holding_open_CM_open_trade_FC,domestic_firm_debt_open_CM_open_trade_FC,
exporter_firm_debt_open_CM_open_trade_FC,avg_Pi_x_open_CM_open_trade_FC,avg_Pi_d_open_CM_open_trade_FC,Profit_fine_x_open_CM_open_trade_FC,
Profit_fine_d_open_CM_open_trade_FC,mean_cons_open_CM_open_trade_FC,sd_cons_open_CM_open_trade_FC,mean_income_open_CM_open_trade_FC,sd_income_open_CM_open_trade_FC,mean_wealth_open_CM_open_trade_FC,
sd_wealth_open_CM_open_trade_FC,wealth_of_workers_open_CM_open_trade_FC,wealth_of_domestic_open_CM_open_trade_FC,wealth_of_exporters_open_CM_open_trade_FC,
income_of_workers_open_CM_open_trade_FC,income_of_domestic_open_CM_open_trade_FC,income_of_exporters_open_CM_open_trade_FC,
cons_of_workers_open_CM_open_trade_FC,cons_of_domestic_open_CM_open_trade_FC,cons_of_exporters_open_CM_open_trade_FC,GINI_wealth_open_CM_open_trade_FC,
GINI_income_open_CM_open_trade_FC,GINI_cons_open_CM_open_trade_FC,p10_wealth_open_CM_open_trade_FC,p50_wealth_open_CM_open_trade_FC,p90_wealth_open_CM_open_trade_FC,p99_wealth_open_CM_open_trade_FC,p10_income_open_CM_open_trade_FC,p50_income_open_CM_open_trade_FC,p90_income_open_CM_open_trade_FC,
p99_income_open_CM_open_trade_FC,p10_cons_open_CM_open_trade_FC,p50_cons_open_CM_open_trade_FC,p90_cons_open_CM_open_trade_FC,p99_cons_open_CM_open_trade_FC,Aggr_bank_cost_open_CM_open_trade_FC,mean_leverage_d_open_CM_open_trade_FC,mean_leverage_x_open_CM_open_trade_FC,mean_leverage_open_CM_open_trade_FC,
sd_leverage_d_open_CM_open_trade_FC,sd_leverage_x_open_CM_open_trade_FC,sd_leverage_open_CM_open_trade_FC,corr_MRPK_lev_d_open_CM_open_trade_FC,corr_MRPK_lev_x_open_CM_open_trade_FC,corr_MRPK_lev_open_CM_open_trade_FC,exit_domestic_to_work_sum_open_CM_open_trade_FC,
exit_exporting_to_work_sum_open_CM_open_trade_FC,mean_growth_rev_open_CM_open_trade_FC,sd_growth_rev_open_CM_open_trade_FC,mean_growth_k_open_CM_open_trade_FC,sd_growth_k_open_CM_open_trade_FC,autocorr_rev_open_CM_open_trade_FC,making_losses_exporter_open_CM_open_trade_FC,
Misallocation_within_d_open_CM_open_trade_FC,Misallocation_within_x_open_CM_open_trade_FC,k_opt_d_fine_open_CM_open_trade_FC,k_opt_x_fine_open_CM_open_trade_FC,V_saved_fine_open_CM_open_trade_FC,avg_rev_xx_entrants_open_CM_open_trade_FC,NFA_open_CM_open_trade_FC) = Residual_stst_detailed(prices_open_CM_open_trade_FC, open_CM_open_trade_parameter_FC);
#end
