include("code_new.jl")
#using Plotly

#@everywhere begin
#Pre - trade liberalization
prices_initial_fl = [   0.18541682174902613,
 0.38138261605992946,
 0.18119612779734,
 2.0978644985564205,
 1.4264816245108158,
 0.18358094660313393,
 0.05158214650892567];

τ_closed_trade = 0.525; #Final bilateral low tariff state
Baseline_parameter.τ = τ_closed_trade * [1.0,1.0];

(residual_initial_fl,a_prime_fine_initial_fl,future_occupation_fine_initial_fl,cons_fine_initial_fl,rev_d_fine_store_initial_fl,
rev_dx_fine_store_initial_fl,rev_xx_fine_store_initial_fl,coeff_final_initial_fl,k_x_fine_initial_fl,k_d_fine_initial_fl,
l_x_fine_initial_fl,l_d_fine_initial_fl,current_distr_store_initial_fl,distr_current_initial_fl,exitflag_initial_fl,domestic_prod_initial_fl,exporter_pop_initial_fl,
domestic_pop_initial_fl,worker_pop_initial_fl,entry_share_to_domestic_initial_fl,exit_share_to_domestic_initial_fl,
entry_share_to_exporter_initial_fl,exit_share_to_worker_initial_fl,total_entry_cost_initial_fl,
total_incumbents_cost_initial_fl,total_exit_cost_initial_fl,labor_excess_demand_initial_fl,labor_demand_initial_fl,
total_consumption_initial_fl,capital_demand_initial_fl,capital_next_initial_fl,
total_demand_final_good_initial_fl,excess_demand_final_good_initial_fl,GDP_initial_fl,nomGDP_initial_fl,PPI_initial_fl,TFP_initial_fl,
TFP_within_initial_fl,TFP_across_initial_fl,TFP_second_best_initial_fl,TOT_initial_fl,TFP_d_initial_fl,
TFP_d_efficient_initial_fl,TFP_x_initial_fl,TFP_x_efficient_initial_fl,total_production_initial_fl,
domestic_price_sum_initial_fl,export_value_initial_fl,investment_initial_fl,
export_value_initial_fl,L_x_initial_fl,L_d_initial_fl,K_x_initial_fl,K_d_initial_fl,x_k_initial_fl,x_l_initial_fl,D_d_initial_fl,D_x_initial_fl,D_d_denom_initial_fl,D_x_denom_initial_fl,
D_d_eff_initial_fl,D_x_eff_initial_fl,D_d_denom_eff_initial_fl,D_x_denom_eff_initial_fl,K_d_ratio_initial_fl,K_x_ratio_initial_fl,
L_d_ratio_initial_fl,L_x_ratio_initial_fl,K_x_ratio_eff_initial_fl,K_d_ratio_eff_initial_fl,L_d_ratio_eff_initial_fl,
L_x_ratio_eff_initial_fl,nomGDP_d_initial_fl,nomGDP_xd_initial_fl,nomGDP_xx_initial_fl,RGDP_d_initial_fl,RGDP_xd_initial_fl,RGDP_xx_initial_fl,RGDP_initial_fl,
mean_MRPK_d_initial_fl,mean_MRPK_x_initial_fl,sd_MRPK_d_initial_fl,sd_MRPK_x_initial_fl,mean_MRPK_initial_fl,sd_MRPK_initial_fl,
mean_MRPL_d_initial_fl,mean_MRPL_x_initial_fl,sd_MRPL_d_initial_fl,sd_MRPL_x_initial_fl,mean_MRPL_initial_fl,sd_MRPL_initial_fl,
cov_TFPR_z_d_initial_fl,cov_TFPR_z_x_initial_fl,cov_TFPR_z_initial_fl,corr_TFPR_z_d_initial_fl,corr_TFPR_z_x_initial_fl,
corr_TFPR_z_initial_fl,mean_logProd_d_initial_fl,mean_logProd_x_initial_fl,mean_logProd_initial_fl,sd_logProd_d_initial_fl,
sd_logProd_x_initial_fl,sd_logProd_initial_fl,import_share_initial_fl,worker_bond_holding_initial_fl,
domestic_bond_holding_initial_fl,exporter_bond_holding_initial_fl,domestic_firm_debt_initial_fl,
exporter_firm_debt_initial_fl,avg_Pi_x_initial_fl,avg_Pi_d_initial_fl,Profit_fine_x_initial_fl,
Profit_fine_d_initial_fl,mean_cons_initial_fl,sd_cons_initial_fl,mean_income_initial_fl,sd_income_initial_fl,mean_wealth_initial_fl,
sd_wealth_initial_fl,wealth_of_workers_initial_fl,wealth_of_domestic_initial_fl,wealth_of_exporters_initial_fl,
income_of_workers_initial_fl,income_of_domestic_initial_fl,income_of_exporters_initial_fl,
cons_of_workers_initial_fl,cons_of_domestic_initial_fl,cons_of_exporters_initial_fl,GINI_wealth_initial_fl,
GINI_income_initial_fl,GINI_cons_initial_fl,p10_wealth_initial_fl,p50_wealth_initial_fl,p90_wealth_initial_fl,p99_wealth_initial_fl,p10_income_initial_fl,p50_income_initial_fl,p90_income_initial_fl,
p99_income_initial_fl,p10_cons_initial_fl,p50_cons_initial_fl,p90_cons_initial_fl,p99_cons_initial_fl,Aggr_bank_cost_initial_fl,mean_leverage_d_initial_fl,mean_leverage_x_initial_fl,mean_leverage_initial_fl,
sd_leverage_d_initial_fl,sd_leverage_x_initial_fl,sd_leverage_initial_fl,corr_MRPK_lev_d_initial_fl,corr_MRPK_lev_x_initial_fl,corr_MRPK_lev_initial_fl,exit_domestic_to_work_sum_initial_fl,
exit_exporting_to_work_sum_initial_fl,mean_growth_rev_initial_fl,sd_growth_rev_initial_fl,mean_growth_k_initial_fl,sd_growth_k_initial_fl,autocorr_rev_initial_fl,
fraction_zombie_exporter_initial_fl,Misallocation_within_d_initial_fl,Misallocation_within_x_initial_fl) = Residual_stst_detailed_frictionless(prices_initial_fl, Baseline_parameter);

#Closed capital markets and after trade liberalization
closed_CM_open_trade_fl_parameter = copy(Baseline_parameter);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_fl_parameter.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade_fl = [ 0.18156300091226313,
 0.38045581525779726,
 0.17937974530488798,
 2.0816225245356965,
 1.3023931004598752,
 0.1865346058399233,
 0.05159183078177525];

(residual_closed_CM_open_trade_fl,a_prime_fine_closed_CM_open_trade_fl,future_occupation_fine_closed_CM_open_trade_fl,cons_fine_closed_CM_open_trade_fl,rev_d_fine_store_closed_CM_open_trade_fl,
rev_dx_fine_store_closed_CM_open_trade_fl,rev_xx_fine_store_closed_CM_open_trade_fl,coeff_final_closed_CM_open_trade_fl,k_x_fine_closed_CM_open_trade_fl,k_d_fine_closed_CM_open_trade_fl,
l_x_fine_closed_CM_open_trade_fl,l_d_fine_closed_CM_open_trade_fl,current_distr_store_closed_CM_open_trade_fl,distr_current_closed_CM_open_trade_fl,exitflag_closed_CM_open_trade_fl,domestic_prod_closed_CM_open_trade_fl,exporter_pop_closed_CM_open_trade_fl,
domestic_pop_closed_CM_open_trade_fl,worker_pop_closed_CM_open_trade_fl,entry_share_to_domestic_closed_CM_open_trade_fl,exit_share_to_domestic_closed_CM_open_trade_fl,
entry_share_to_exporter_closed_CM_open_trade_fl,exit_share_to_worker_closed_CM_open_trade_fl,total_entry_cost_closed_CM_open_trade_fl,
total_incumbents_cost_closed_CM_open_trade_fl,total_exit_cost_closed_CM_open_trade_fl,labor_excess_demand_closed_CM_open_trade_fl,labor_demand_closed_CM_open_trade_fl,
total_consumption_closed_CM_open_trade_fl,capital_demand_closed_CM_open_trade_fl,capital_next_closed_CM_open_trade_fl,
total_demand_final_good_closed_CM_open_trade_fl,excess_demand_final_good_closed_CM_open_trade_fl,GDP_closed_CM_open_trade_fl,nomGDP_closed_CM_open_trade_fl,PPI_closed_CM_open_trade_fl,TFP_closed_CM_open_trade_fl,
TFP_within_closed_CM_open_trade_fl,TFP_across_closed_CM_open_trade_fl,TFP_second_best_closed_CM_open_trade_fl,TOT_closed_CM_open_trade_fl,TFP_d_closed_CM_open_trade_fl,
TFP_d_efficient_closed_CM_open_trade_fl,TFP_x_closed_CM_open_trade_fl,TFP_x_efficient_closed_CM_open_trade_fl,total_production_closed_CM_open_trade_fl,
domestic_price_sum_closed_CM_open_trade_fl,export_value_closed_CM_open_trade_fl,investment_closed_CM_open_trade_fl,
export_value_closed_CM_open_trade_fl,L_x_closed_CM_open_trade_fl,L_d_closed_CM_open_trade_fl,K_x_closed_CM_open_trade_fl,K_d_closed_CM_open_trade_fl,x_k_closed_CM_open_trade_fl,x_l_closed_CM_open_trade_fl,D_d_closed_CM_open_trade_fl,D_x_closed_CM_open_trade_fl,D_d_denom_closed_CM_open_trade_fl,D_x_denom_closed_CM_open_trade_fl,
D_d_eff_closed_CM_open_trade_fl,D_x_eff_closed_CM_open_trade_fl,D_d_denom_eff_closed_CM_open_trade_fl,D_x_denom_eff_closed_CM_open_trade_fl,K_d_ratio_closed_CM_open_trade_fl,K_x_ratio_closed_CM_open_trade_fl,
L_d_ratio_closed_CM_open_trade_fl,L_x_ratio_closed_CM_open_trade_fl,K_x_ratio_eff_closed_CM_open_trade_fl,K_d_ratio_eff_closed_CM_open_trade_fl,L_d_ratio_eff_closed_CM_open_trade_fl,
L_x_ratio_eff_closed_CM_open_trade_fl,nomGDP_d_closed_CM_open_trade_fl,nomGDP_xd_closed_CM_open_trade_fl,nomGDP_xx_closed_CM_open_trade_fl,RGDP_d_closed_CM_open_trade_fl,RGDP_xd_closed_CM_open_trade_fl,RGDP_xx_closed_CM_open_trade_fl,RGDP_closed_CM_open_trade_fl,
mean_MRPK_d_closed_CM_open_trade_fl,mean_MRPK_x_closed_CM_open_trade_fl,sd_MRPK_d_closed_CM_open_trade_fl,sd_MRPK_x_closed_CM_open_trade_fl,mean_MRPK_closed_CM_open_trade_fl,sd_MRPK_closed_CM_open_trade_fl,
mean_MRPL_d_closed_CM_open_trade_fl,mean_MRPL_x_closed_CM_open_trade_fl,sd_MRPL_d_closed_CM_open_trade_fl,sd_MRPL_x_closed_CM_open_trade_fl,mean_MRPL_closed_CM_open_trade_fl,sd_MRPL_closed_CM_open_trade_fl,
cov_TFPR_z_d_closed_CM_open_trade_fl,cov_TFPR_z_x_closed_CM_open_trade_fl,cov_TFPR_z_closed_CM_open_trade_fl,corr_TFPR_z_d_closed_CM_open_trade_fl,corr_TFPR_z_x_closed_CM_open_trade_fl,
corr_TFPR_z_closed_CM_open_trade_fl,mean_logProd_d_closed_CM_open_trade_fl,mean_logProd_x_closed_CM_open_trade_fl,mean_logProd_closed_CM_open_trade_fl,sd_logProd_d_closed_CM_open_trade_fl,
sd_logProd_x_closed_CM_open_trade_fl,sd_logProd_closed_CM_open_trade_fl,import_share_closed_CM_open_trade_fl,worker_bond_holding_closed_CM_open_trade_fl,
domestic_bond_holding_closed_CM_open_trade_fl,exporter_bond_holding_closed_CM_open_trade_fl,domestic_firm_debt_closed_CM_open_trade_fl,
exporter_firm_debt_closed_CM_open_trade_fl,avg_Pi_x_closed_CM_open_trade_fl,avg_Pi_d_closed_CM_open_trade_fl,Profit_fine_x_closed_CM_open_trade_fl,
Profit_fine_d_closed_CM_open_trade_fl,mean_cons_closed_CM_open_trade_fl,sd_cons_closed_CM_open_trade_fl,mean_income_closed_CM_open_trade_fl,sd_income_closed_CM_open_trade_fl,mean_wealth_closed_CM_open_trade_fl,
sd_wealth_closed_CM_open_trade_fl,wealth_of_workers_closed_CM_open_trade_fl,wealth_of_domestic_closed_CM_open_trade_fl,wealth_of_exporters_closed_CM_open_trade_fl,
income_of_workers_closed_CM_open_trade_fl,income_of_domestic_closed_CM_open_trade_fl,income_of_exporters_closed_CM_open_trade_fl,
cons_of_workers_closed_CM_open_trade_fl,cons_of_domestic_closed_CM_open_trade_fl,cons_of_exporters_closed_CM_open_trade_fl,GINI_wealth_closed_CM_open_trade_fl,
GINI_income_closed_CM_open_trade_fl,GINI_cons_closed_CM_open_trade_fl,p10_wealth_closed_CM_open_trade_fl,p50_wealth_closed_CM_open_trade_fl,p90_wealth_closed_CM_open_trade_fl,p99_wealth_closed_CM_open_trade_fl,p10_income_closed_CM_open_trade_fl,p50_income_closed_CM_open_trade_fl,p90_income_closed_CM_open_trade_fl,
p99_income_closed_CM_open_trade_fl,p10_cons_closed_CM_open_trade_fl,p50_cons_closed_CM_open_trade_fl,p90_cons_closed_CM_open_trade_fl,p99_cons_closed_CM_open_trade_fl,Aggr_bank_cost_closed_CM_open_trade_fl,mean_leverage_d_closed_CM_open_trade_fl,mean_leverage_x_closed_CM_open_trade_fl,mean_leverage_closed_CM_open_trade_fl,
sd_leverage_d_closed_CM_open_trade_fl,sd_leverage_x_closed_CM_open_trade_fl,sd_leverage_closed_CM_open_trade_fl,corr_MRPK_lev_d_closed_CM_open_trade_fl,corr_MRPK_lev_x_closed_CM_open_trade_fl,corr_MRPK_lev_closed_CM_open_trade_fl,exit_domestic_to_work_sum_closed_CM_open_trade_fl,
exit_exporting_to_work_sum_closed_CM_open_trade_fl,mean_growth_rev_closed_CM_open_trade_fl,sd_growth_rev_closed_CM_open_trade_fl,mean_growth_k_closed_CM_open_trade_fl,sd_growth_k_closed_CM_open_trade_fl,autocorr_rev_closed_CM_open_trade_fl,fraction_zombie_exporter_closed_CM_open_trade_fl,
Misallocation_within_d_closed_CM_open_trade_fl,Misallocation_within_x_closed_CM_open_trade_fl) = Residual_stst_detailed_frictionless(prices_closed_CM_open_trade_fl, closed_CM_open_trade_fl_parameter);

#Open capital markets and after trade liberalization
open_CM_open_trade_fl_parameter = copy(Baseline_parameter);
open_CM_open_trade_fl_parameter.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_fl_parameter.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade_fl =  [    0.22688340229996265,
 0.3949933847221664,
 0.23177944709080556,
 2.3691825528711123,
 1.2339615218304878,
 0.05080430544231692];

(residual_open_CM_open_trade_fl,a_prime_fine_open_CM_open_trade_fl,future_occupation_fine_open_CM_open_trade_fl,cons_fine_open_CM_open_trade_fl,rev_d_fine_store_open_CM_open_trade_fl,
rev_dx_fine_store_open_CM_open_trade_fl,rev_xx_fine_store_open_CM_open_trade_fl,coeff_final_open_CM_open_trade_fl,k_x_fine_open_CM_open_trade_fl,k_d_fine_open_CM_open_trade_fl,
l_x_fine_open_CM_open_trade_fl,l_d_fine_open_CM_open_trade_fl,current_distr_store_open_CM_open_trade_fl,distr_current_open_CM_open_trade_fl,exitflag_open_CM_open_trade_fl,domestic_prod_open_CM_open_trade_fl,exporter_pop_open_CM_open_trade_fl,
domestic_pop_open_CM_open_trade_fl,worker_pop_open_CM_open_trade_fl,entry_share_to_domestic_open_CM_open_trade_fl,exit_share_to_domestic_open_CM_open_trade_fl,
entry_share_to_exporter_open_CM_open_trade_fl,exit_share_to_worker_open_CM_open_trade_fl,total_entry_cost_open_CM_open_trade_fl,
total_incumbents_cost_open_CM_open_trade_fl,total_exit_cost_open_CM_open_trade_fl,labor_excess_demand_open_CM_open_trade_fl,labor_demand_open_CM_open_trade_fl,
total_consumption_open_CM_open_trade_fl,capital_demand_open_CM_open_trade_fl,capital_next_open_CM_open_trade_fl,
total_demand_final_good_open_CM_open_trade_fl,excess_demand_final_good_open_CM_open_trade_fl,GDP_open_CM_open_trade_fl,nomGDP_open_CM_open_trade_fl,PPI_open_CM_open_trade_fl,TFP_open_CM_open_trade_fl,
TFP_within_open_CM_open_trade_fl,TFP_across_open_CM_open_trade_fl,TFP_second_best_open_CM_open_trade_fl,TOT_open_CM_open_trade_fl,TFP_d_open_CM_open_trade_fl,
TFP_d_efficient_open_CM_open_trade_fl,TFP_x_open_CM_open_trade_fl,TFP_x_efficient_open_CM_open_trade_fl,total_production_open_CM_open_trade_fl,
domestic_price_sum_open_CM_open_trade_fl,export_value_open_CM_open_trade_fl,investment_open_CM_open_trade_fl,
export_value_open_CM_open_trade_fl,L_x_open_CM_open_trade_fl,L_d_open_CM_open_trade_fl,K_x_open_CM_open_trade_fl,K_d_open_CM_open_trade_fl,x_k_open_CM_open_trade_fl,x_l_open_CM_open_trade_fl,D_d_open_CM_open_trade_fl,D_x_open_CM_open_trade_fl,D_d_denom_open_CM_open_trade_fl,D_x_denom_open_CM_open_trade_fl,
D_d_eff_open_CM_open_trade_fl,D_x_eff_open_CM_open_trade_fl,D_d_denom_eff_open_CM_open_trade_fl,D_x_denom_eff_open_CM_open_trade_fl,K_d_ratio_open_CM_open_trade_fl,K_x_ratio_open_CM_open_trade_fl,
L_d_ratio_open_CM_open_trade_fl,L_x_ratio_open_CM_open_trade_fl,K_x_ratio_eff_open_CM_open_trade_fl,K_d_ratio_eff_open_CM_open_trade_fl,L_d_ratio_eff_open_CM_open_trade_fl,
L_x_ratio_eff_open_CM_open_trade_fl,nomGDP_d_open_CM_open_trade_fl,nomGDP_xd_open_CM_open_trade_fl,nomGDP_xx_open_CM_open_trade_fl,RGDP_d_open_CM_open_trade_fl,RGDP_xd_open_CM_open_trade_fl,RGDP_xx_open_CM_open_trade_fl,RGDP_open_CM_open_trade_fl,
mean_MRPK_d_open_CM_open_trade_fl,mean_MRPK_x_open_CM_open_trade_fl,sd_MRPK_d_open_CM_open_trade_fl,sd_MRPK_x_open_CM_open_trade_fl,mean_MRPK_open_CM_open_trade_fl,sd_MRPK_open_CM_open_trade_fl,
mean_MRPL_d_open_CM_open_trade_fl,mean_MRPL_x_open_CM_open_trade_fl,sd_MRPL_d_open_CM_open_trade_fl,sd_MRPL_x_open_CM_open_trade_fl,mean_MRPL_open_CM_open_trade_fl,sd_MRPL_open_CM_open_trade_fl,
cov_TFPR_z_d_open_CM_open_trade_fl,cov_TFPR_z_x_open_CM_open_trade_fl,cov_TFPR_z_open_CM_open_trade_fl,corr_TFPR_z_d_open_CM_open_trade_fl,corr_TFPR_z_x_open_CM_open_trade_fl,
corr_TFPR_z_open_CM_open_trade_fl,mean_logProd_d_open_CM_open_trade_fl,mean_logProd_x_open_CM_open_trade_fl,mean_logProd_open_CM_open_trade_fl,sd_logProd_d_open_CM_open_trade_fl,
sd_logProd_x_open_CM_open_trade_fl,sd_logProd_open_CM_open_trade_fl,import_share_open_CM_open_trade_fl,worker_bond_holding_open_CM_open_trade_fl,
domestic_bond_holding_open_CM_open_trade_fl,exporter_bond_holding_open_CM_open_trade_fl,domestic_firm_debt_open_CM_open_trade_fl,
exporter_firm_debt_open_CM_open_trade_fl,avg_Pi_x_open_CM_open_trade_fl,avg_Pi_d_open_CM_open_trade_fl,Profit_fine_x_open_CM_open_trade_fl,
Profit_fine_d_open_CM_open_trade_fl,mean_cons_open_CM_open_trade_fl,sd_cons_open_CM_open_trade_fl,mean_income_open_CM_open_trade_fl,sd_income_open_CM_open_trade_fl,mean_wealth_open_CM_open_trade_fl,
sd_wealth_open_CM_open_trade_fl,wealth_of_workers_open_CM_open_trade_fl,wealth_of_domestic_open_CM_open_trade_fl,wealth_of_exporters_open_CM_open_trade_fl,
income_of_workers_open_CM_open_trade_fl,income_of_domestic_open_CM_open_trade_fl,income_of_exporters_open_CM_open_trade_fl,
cons_of_workers_open_CM_open_trade_fl,cons_of_domestic_open_CM_open_trade_fl,cons_of_exporters_open_CM_open_trade_fl,GINI_wealth_open_CM_open_trade_fl,
GINI_income_open_CM_open_trade_fl,GINI_cons_open_CM_open_trade_fl,p10_wealth_open_CM_open_trade_fl,p50_wealth_open_CM_open_trade_fl,p90_wealth_open_CM_open_trade_fl,p99_wealth_open_CM_open_trade_fl,p10_income_open_CM_open_trade_fl,p50_income_open_CM_open_trade_fl,p90_income_open_CM_open_trade_fl,
p99_income_open_CM_open_trade_fl,p10_cons_open_CM_open_trade_fl,p50_cons_open_CM_open_trade_fl,p90_cons_open_CM_open_trade_fl,p99_cons_open_CM_open_trade_fl,Aggr_bank_cost_open_CM_open_trade_fl,mean_leverage_d_open_CM_open_trade_fl,mean_leverage_x_open_CM_open_trade_fl,mean_leverage_open_CM_open_trade_fl,
sd_leverage_d_open_CM_open_trade_fl,sd_leverage_x_open_CM_open_trade_fl,sd_leverage_open_CM_open_trade_fl,corr_MRPK_lev_d_open_CM_open_trade_fl,corr_MRPK_lev_x_open_CM_open_trade_fl,corr_MRPK_lev_open_CM_open_trade_fl,exit_domestic_to_work_sum_open_CM_open_trade_fl,
exit_exporting_to_work_sum_open_CM_open_trade_fl,mean_growth_rev_open_CM_open_trade_fl,sd_growth_rev_open_CM_open_trade_fl,mean_growth_k_open_CM_open_trade_fl,sd_growth_k_open_CM_open_trade_fl,autocorr_rev_open_CM_open_trade_fl,fraction_zombie_exporter_open_CM_open_trade_fl,
Misallocation_within_d_open_CM_open_trade_fl,Misallocation_within_x_open_CM_open_trade_fl) = Residual_stst_detailed_frictionless(prices_open_CM_open_trade_fl, open_CM_open_trade_fl_parameter);
#end
#Open capital markets but no trade liberalization
open_CM_closed_trade_fl_parameter = copy(Baseline_parameter);
open_CM_closed_trade_fl_parameter.openness = 1;

τ_closed_trade = 0.525;
open_CM_closed_trade_fl_parameter.τ = τ_closed_trade * [1.0,1.0];
prices_open_CM_closed_trade_fl =  [   0.22621878884933877,
 0.3998343536209743,
 0.22066036440275072,
 2.45688085758235,
 1.365131420206826,
 0.050828124117371955];

(residual_open_CM_closed_trade_fl,a_prime_fine_open_CM_closed_trade_fl,future_occupation_fine_open_CM_closed_trade_fl,cons_fine_open_CM_closed_trade_fl,rev_d_fine_store_open_CM_closed_trade_fl,
rev_dx_fine_store_open_CM_closed_trade_fl,rev_xx_fine_store_open_CM_closed_trade_fl,coeff_final_open_CM_closed_trade_fl,k_x_fine_open_CM_closed_trade_fl,k_d_fine_open_CM_closed_trade_fl,
l_x_fine_open_CM_closed_trade_fl,l_d_fine_open_CM_closed_trade_fl,current_distr_store_open_CM_closed_trade_fl,distr_current_open_CM_closed_trade_fl,exitflag_open_CM_closed_trade_fl,domestic_prod_open_CM_closed_trade_fl,exporter_pop_open_CM_closed_trade_fl,
domestic_pop_open_CM_closed_trade_fl,worker_pop_open_CM_closed_trade_fl,entry_share_to_domestic_open_CM_closed_trade_fl,exit_share_to_domestic_open_CM_closed_trade_fl,
entry_share_to_exporter_open_CM_closed_trade_fl,exit_share_to_worker_open_CM_closed_trade_fl,total_entry_cost_open_CM_closed_trade_fl,
total_incumbents_cost_open_CM_closed_trade_fl,total_exit_cost_open_CM_closed_trade_fl,labor_excess_demand_open_CM_closed_trade_fl,labor_demand_open_CM_closed_trade_fl,
total_consumption_open_CM_closed_trade_fl,capital_demand_open_CM_closed_trade_fl,capital_next_open_CM_closed_trade_fl,
total_demand_final_good_open_CM_closed_trade_fl,excess_demand_final_good_open_CM_closed_trade_fl,GDP_open_CM_closed_trade_fl,nomGDP_open_CM_closed_trade_fl,PPI_open_CM_closed_trade_fl,TFP_open_CM_closed_trade_fl,
TFP_within_open_CM_closed_trade_fl,TFP_across_open_CM_closed_trade_fl,TFP_second_best_open_CM_closed_trade_fl,TOT_open_CM_closed_trade_fl,TFP_d_open_CM_closed_trade_fl,
TFP_d_efficient_open_CM_closed_trade_fl,TFP_x_open_CM_closed_trade_fl,TFP_x_efficient_open_CM_closed_trade_fl,total_production_open_CM_closed_trade_fl,
domestic_price_sum_open_CM_closed_trade_fl,export_value_open_CM_closed_trade_fl,investment_open_CM_closed_trade_fl,
export_value_open_CM_closed_trade_fl,L_x_open_CM_closed_trade_fl,L_d_open_CM_closed_trade_fl,K_x_open_CM_closed_trade_fl,K_d_open_CM_closed_trade_fl,x_k_open_CM_closed_trade_fl,x_l_open_CM_closed_trade_fl,D_d_open_CM_closed_trade_fl,D_x_open_CM_closed_trade_fl,D_d_denom_open_CM_closed_trade_fl,D_x_denom_open_CM_closed_trade_fl,
D_d_eff_open_CM_closed_trade_fl,D_x_eff_open_CM_closed_trade_fl,D_d_denom_eff_open_CM_closed_trade_fl,D_x_denom_eff_open_CM_closed_trade_fl,K_d_ratio_open_CM_closed_trade_fl,K_x_ratio_open_CM_closed_trade_fl,
L_d_ratio_open_CM_closed_trade_fl,L_x_ratio_open_CM_closed_trade_fl,K_x_ratio_eff_open_CM_closed_trade_fl,K_d_ratio_eff_open_CM_closed_trade_fl,L_d_ratio_eff_open_CM_closed_trade_fl,
L_x_ratio_eff_open_CM_closed_trade_fl,nomGDP_d_open_CM_closed_trade_fl,nomGDP_xd_open_CM_closed_trade_fl,nomGDP_xx_open_CM_closed_trade_fl,RGDP_d_open_CM_closed_trade_fl,RGDP_xd_open_CM_closed_trade_fl,RGDP_xx_open_CM_closed_trade_fl,RGDP_open_CM_closed_trade_fl,
mean_MRPK_d_open_CM_closed_trade_fl,mean_MRPK_x_open_CM_closed_trade_fl,sd_MRPK_d_open_CM_closed_trade_fl,sd_MRPK_x_open_CM_closed_trade_fl,mean_MRPK_open_CM_closed_trade_fl,sd_MRPK_open_CM_closed_trade_fl,
mean_MRPL_d_open_CM_closed_trade_fl,mean_MRPL_x_open_CM_closed_trade_fl,sd_MRPL_d_open_CM_closed_trade_fl,sd_MRPL_x_open_CM_closed_trade_fl,mean_MRPL_open_CM_closed_trade_fl,sd_MRPL_open_CM_closed_trade_fl,
cov_TFPR_z_d_open_CM_closed_trade_fl,cov_TFPR_z_x_open_CM_closed_trade_fl,cov_TFPR_z_open_CM_closed_trade_fl,corr_TFPR_z_d_open_CM_closed_trade_fl,corr_TFPR_z_x_open_CM_closed_trade_fl,
corr_TFPR_z_open_CM_closed_trade_fl,mean_logProd_d_open_CM_closed_trade_fl,mean_logProd_x_open_CM_closed_trade_fl,mean_logProd_open_CM_closed_trade_fl,sd_logProd_d_open_CM_closed_trade_fl,
sd_logProd_x_open_CM_closed_trade_fl,sd_logProd_open_CM_closed_trade_fl,import_share_open_CM_closed_trade_fl,worker_bond_holding_open_CM_closed_trade_fl,
domestic_bond_holding_open_CM_closed_trade_fl,exporter_bond_holding_open_CM_closed_trade_fl,domestic_firm_debt_open_CM_closed_trade_fl,
exporter_firm_debt_open_CM_closed_trade_fl,avg_Pi_x_open_CM_closed_trade_fl,avg_Pi_d_open_CM_closed_trade_fl,Profit_fine_x_open_CM_closed_trade_fl,
Profit_fine_d_open_CM_closed_trade_fl,mean_cons_open_CM_closed_trade_fl,sd_cons_open_CM_closed_trade_fl,mean_income_open_CM_closed_trade_fl,sd_income_open_CM_closed_trade_fl,mean_wealth_open_CM_closed_trade_fl,
sd_wealth_open_CM_closed_trade_fl,wealth_of_workers_open_CM_closed_trade_fl,wealth_of_domestic_open_CM_closed_trade_fl,wealth_of_exporters_open_CM_closed_trade_fl,
income_of_workers_open_CM_closed_trade_fl,income_of_domestic_open_CM_closed_trade_fl,income_of_exporters_open_CM_closed_trade_fl,
cons_of_workers_open_CM_closed_trade_fl,cons_of_domestic_open_CM_closed_trade_fl,cons_of_exporters_open_CM_closed_trade_fl,GINI_wealth_open_CM_closed_trade_fl,
GINI_income_open_CM_closed_trade_fl,GINI_cons_open_CM_closed_trade_fl,p10_wealth_open_CM_closed_trade_fl,p50_wealth_open_CM_closed_trade_fl,p90_wealth_open_CM_closed_trade_fl,p99_wealth_open_CM_closed_trade_fl,p10_income_open_CM_closed_trade_fl,p50_income_open_CM_closed_trade_fl,p90_income_open_CM_closed_trade_fl,
p99_income_open_CM_closed_trade_fl,p10_cons_open_CM_closed_trade_fl,p50_cons_open_CM_closed_trade_fl,p90_cons_open_CM_closed_trade_fl,p99_cons_open_CM_closed_trade_fl,Aggr_bank_cost_open_CM_closed_trade_fl,mean_leverage_d_open_CM_closed_trade_fl,mean_leverage_x_open_CM_closed_trade_fl,mean_leverage_open_CM_closed_trade_fl,
sd_leverage_d_open_CM_closed_trade_fl,sd_leverage_x_open_CM_closed_trade_fl,sd_leverage_open_CM_closed_trade_fl,corr_MRPK_lev_d_open_CM_closed_trade_fl,corr_MRPK_lev_x_open_CM_closed_trade_fl,corr_MRPK_lev_open_CM_closed_trade_fl,exit_domestic_to_work_sum_open_CM_closed_trade_fl,
exit_exporting_to_work_sum_open_CM_closed_trade_fl,mean_growth_rev_open_CM_closed_trade_fl,sd_growth_rev_open_CM_closed_trade_fl,mean_growth_k_open_CM_closed_trade_fl,sd_growth_k_open_CM_closed_trade_fl,autocorr_rev_open_CM_closed_trade_fl,fraction_zombie_exporter_open_CM_closed_trade_fl,
Misallocation_within_d_open_CM_closed_trade_fl,Misallocation_within_x_open_CM_closed_trade_fl) = Residual_stst_detailed_frictionless(prices_open_CM_closed_trade_fl, open_CM_closed_trade_fl_parameter);
#end
