# ============================================================================
# main_script.jl
#
# Entry point for the steady-state analysis. Includes code_new.jl, then
# solves for four steady-state equilibria via Residual_stst_detailed:
#
#   initial               : pre-trade-liberalisation, closed capital markets
#   closed_CM_open_trade  : post-trade-liberalisation, closed capital markets
#   open_CM_open_trade    : post-trade-liberalisation, open capital markets
#   open_CM_closed_trade  : pre-trade-liberalisation, open capital markets
#
# Each call stores the full set of aggregates and distributional statistics
# for subsequent comparison and welfare analysis.
# ============================================================================
include("code_new.jl")
#using Plotly

#@everywhere begin
#Pre - trade liberalization
prices_initial = [ 0.15528441758090944,
 0.3784430527380479,
 0.14699088915393219,
 2.2498576253833327,
 1.388343782317246,
 0.13518926781029914,
 0.04907462592267907];

τ_closed_trade = 0.525; #Final bilateral low tariff state
Baseline_parameter.τ = τ_closed_trade * [1.0,1.0];

(residual_initial,a_prime_fine_initial,future_occupation_fine_initial,cons_fine_initial,rev_d_fine_store_initial,
rev_dx_fine_store_initial,rev_xx_fine_store_initial,coeff_final_initial,k_x_fine_initial,k_d_fine_initial,
l_x_fine_initial,l_d_fine_initial,current_distr_store_initial,distr_current_initial,exitflag_initial,domestic_prod_initial,exporter_pop_initial,
domestic_pop_initial,worker_pop_initial,entry_share_to_domestic_initial,exit_share_to_domestic_initial,
entry_share_to_exporter_initial,exit_share_to_worker_initial,total_entry_cost_initial,
total_incumbents_cost_initial,total_exit_cost_initial,labor_excess_demand_initial,labor_demand_initial,
total_consumption_initial,capital_demand_initial,capital_next_initial,
total_demand_final_good_initial,excess_demand_final_good_initial,GDP_initial,nomGDP_initial,PPI_initial,TFP_initial,
TFP_within_initial,TFP_across_initial,TFP_second_best_initial,TOT_initial,TFP_d_initial,
TFP_d_efficient_initial,TFP_x_initial,TFP_x_efficient_initial,total_production_initial,
domestic_price_sum_initial,export_value_initial,investment_initial,
L_x_initial,L_d_initial,K_x_initial,K_d_initial,x_k_initial,x_l_initial,D_d_initial,D_x_initial,D_d_denom_initial,D_x_denom_initial,
D_d_eff_initial,D_x_eff_initial,D_d_denom_eff_initial,D_x_denom_eff_initial,K_d_ratio_initial,K_x_ratio_initial,
L_d_ratio_initial,L_x_ratio_initial,K_x_ratio_eff_initial,K_d_ratio_eff_initial,L_d_ratio_eff_initial,
L_x_ratio_eff_initial,nomGDP_d_initial,nomGDP_xd_initial,nomGDP_xx_initial,RGDP_d_initial,RGDP_xd_initial,RGDP_xx_initial,RGDP_initial,
mean_MRPK_d_initial,mean_MRPK_x_initial,sd_MRPK_d_initial,sd_MRPK_x_initial,mean_MRPK_initial,sd_MRPK_initial,
mean_MRPL_d_initial,mean_MRPL_x_initial,sd_MRPL_d_initial,sd_MRPL_x_initial,mean_MRPL_initial,sd_MRPL_initial,
cov_TFPR_z_d_initial,cov_TFPR_z_x_initial,cov_TFPR_z_initial,corr_TFPR_z_d_initial,corr_TFPR_z_x_initial,
corr_TFPR_z_initial,mean_logProd_d_initial,mean_logProd_x_initial,mean_logProd_initial,sd_logProd_d_initial,
sd_logProd_x_initial,sd_logProd_initial,import_share_initial,worker_bond_holding_initial,
domestic_bond_holding_initial,exporter_bond_holding_initial,domestic_firm_debt_initial,
exporter_firm_debt_initial,avg_Pi_x_initial,avg_Pi_d_initial,Profit_fine_x_initial,
Profit_fine_d_initial,mean_cons_initial,sd_cons_initial,mean_income_initial,sd_income_initial,mean_wealth_initial,
sd_wealth_initial,wealth_of_workers_initial,wealth_of_domestic_initial,wealth_of_exporters_initial,
income_of_workers_initial,income_of_domestic_initial,income_of_exporters_initial,
cons_of_workers_initial,cons_of_domestic_initial,cons_of_exporters_initial,GINI_wealth_initial,
GINI_income_initial,GINI_cons_initial,p10_wealth_initial,p50_wealth_initial,p90_wealth_initial,p99_wealth_initial,p10_income_initial,p50_income_initial,p90_income_initial,
p99_income_initial,p10_cons_initial,p50_cons_initial,p90_cons_initial,p99_cons_initial,Aggr_bank_cost_initial,mean_leverage_d_initial,mean_leverage_x_initial,mean_leverage_initial,
sd_leverage_d_initial,sd_leverage_x_initial,sd_leverage_initial,corr_MRPK_lev_d_initial,corr_MRPK_lev_x_initial,corr_MRPK_lev_initial,exit_domestic_to_work_sum_initial,
exit_exporting_to_work_sum_initial,mean_growth_rev_initial,sd_growth_rev_initial,mean_growth_k_initial,sd_growth_k_initial,autocorr_rev_initial,
making_losses_exporter_initial,Misallocation_within_d_initial,Misallocation_within_x_initial,k_opt_d_fine_initial,k_opt_x_fine_initial,V_saved_fine_initial,avg_rev_xx_entrants_initial,NFA_initial) = Residual_stst_detailed(prices_initial, Baseline_parameter);

#Closed capital markets and after trade liberalization
closed_CM_open_trade_parameter = copy(Baseline_parameter);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_parameter.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade = [  0.15736639937663147,
0.3697983186132166,
0.15759877959397917,
2.0449626046287253,
1.3252338424810661,
0.13667508873036238,
0.050308422000531754];

(residual_closed_CM_open_trade,a_prime_fine_closed_CM_open_trade,future_occupation_fine_closed_CM_open_trade,cons_fine_closed_CM_open_trade,rev_d_fine_store_closed_CM_open_trade,
rev_dx_fine_store_closed_CM_open_trade,rev_xx_fine_store_closed_CM_open_trade,coeff_final_closed_CM_open_trade,k_x_fine_closed_CM_open_trade,k_d_fine_closed_CM_open_trade,
l_x_fine_closed_CM_open_trade,l_d_fine_closed_CM_open_trade,current_distr_store_closed_CM_open_trade,distr_current_closed_CM_open_trade,exitflag_closed_CM_open_trade,domestic_prod_closed_CM_open_trade,exporter_pop_closed_CM_open_trade,
domestic_pop_closed_CM_open_trade,worker_pop_closed_CM_open_trade,entry_share_to_domestic_closed_CM_open_trade,exit_share_to_domestic_closed_CM_open_trade,
entry_share_to_exporter_closed_CM_open_trade,exit_share_to_worker_closed_CM_open_trade,total_entry_cost_closed_CM_open_trade,
total_incumbents_cost_closed_CM_open_trade,total_exit_cost_closed_CM_open_trade,labor_excess_demand_closed_CM_open_trade,labor_demand_closed_CM_open_trade,
total_consumption_closed_CM_open_trade,capital_demand_closed_CM_open_trade,capital_next_closed_CM_open_trade,
total_demand_final_good_closed_CM_open_trade,excess_demand_final_good_closed_CM_open_trade,GDP_closed_CM_open_trade,nomGDP_closed_CM_open_trade,PPI_closed_CM_open_trade,TFP_closed_CM_open_trade,
TFP_within_closed_CM_open_trade,TFP_across_closed_CM_open_trade,TFP_second_best_closed_CM_open_trade,TOT_closed_CM_open_trade,TFP_d_closed_CM_open_trade,
TFP_d_efficient_closed_CM_open_trade,TFP_x_closed_CM_open_trade,TFP_x_efficient_closed_CM_open_trade,total_production_closed_CM_open_trade,
domestic_price_sum_closed_CM_open_trade,export_value_closed_CM_open_trade,investment_closed_CM_open_trade,
L_x_closed_CM_open_trade,L_d_closed_CM_open_trade,K_x_closed_CM_open_trade,K_d_closed_CM_open_trade,x_k_closed_CM_open_trade,x_l_closed_CM_open_trade,D_d_closed_CM_open_trade,D_x_closed_CM_open_trade,D_d_denom_closed_CM_open_trade,D_x_denom_closed_CM_open_trade,
D_d_eff_closed_CM_open_trade,D_x_eff_closed_CM_open_trade,D_d_denom_eff_closed_CM_open_trade,D_x_denom_eff_closed_CM_open_trade,K_d_ratio_closed_CM_open_trade,K_x_ratio_closed_CM_open_trade,
L_d_ratio_closed_CM_open_trade,L_x_ratio_closed_CM_open_trade,K_x_ratio_eff_closed_CM_open_trade,K_d_ratio_eff_closed_CM_open_trade,L_d_ratio_eff_closed_CM_open_trade,
L_x_ratio_eff_closed_CM_open_trade,nomGDP_d_closed_CM_open_trade,nomGDP_xd_closed_CM_open_trade,nomGDP_xx_closed_CM_open_trade,RGDP_d_closed_CM_open_trade,RGDP_xd_closed_CM_open_trade,RGDP_xx_closed_CM_open_trade,RGDP_closed_CM_open_trade,
mean_MRPK_d_closed_CM_open_trade,mean_MRPK_x_closed_CM_open_trade,sd_MRPK_d_closed_CM_open_trade,sd_MRPK_x_closed_CM_open_trade,mean_MRPK_closed_CM_open_trade,sd_MRPK_closed_CM_open_trade,
mean_MRPL_d_closed_CM_open_trade,mean_MRPL_x_closed_CM_open_trade,sd_MRPL_d_closed_CM_open_trade,sd_MRPL_x_closed_CM_open_trade,mean_MRPL_closed_CM_open_trade,sd_MRPL_closed_CM_open_trade,
cov_TFPR_z_d_closed_CM_open_trade,cov_TFPR_z_x_closed_CM_open_trade,cov_TFPR_z_closed_CM_open_trade,corr_TFPR_z_d_closed_CM_open_trade,corr_TFPR_z_x_closed_CM_open_trade,
corr_TFPR_z_closed_CM_open_trade,mean_logProd_d_closed_CM_open_trade,mean_logProd_x_closed_CM_open_trade,mean_logProd_closed_CM_open_trade,sd_logProd_d_closed_CM_open_trade,
sd_logProd_x_closed_CM_open_trade,sd_logProd_closed_CM_open_trade,import_share_closed_CM_open_trade,worker_bond_holding_closed_CM_open_trade,
domestic_bond_holding_closed_CM_open_trade,exporter_bond_holding_closed_CM_open_trade,domestic_firm_debt_closed_CM_open_trade,
exporter_firm_debt_closed_CM_open_trade,avg_Pi_x_closed_CM_open_trade,avg_Pi_d_closed_CM_open_trade,Profit_fine_x_closed_CM_open_trade,
Profit_fine_d_closed_CM_open_trade,mean_cons_closed_CM_open_trade,sd_cons_closed_CM_open_trade,mean_income_closed_CM_open_trade,sd_income_closed_CM_open_trade,mean_wealth_closed_CM_open_trade,
sd_wealth_closed_CM_open_trade,wealth_of_workers_closed_CM_open_trade,wealth_of_domestic_closed_CM_open_trade,wealth_of_exporters_closed_CM_open_trade,
income_of_workers_closed_CM_open_trade,income_of_domestic_closed_CM_open_trade,income_of_exporters_closed_CM_open_trade,
cons_of_workers_closed_CM_open_trade,cons_of_domestic_closed_CM_open_trade,cons_of_exporters_closed_CM_open_trade,GINI_wealth_closed_CM_open_trade,
GINI_income_closed_CM_open_trade,GINI_cons_closed_CM_open_trade,p10_wealth_closed_CM_open_trade,p50_wealth_closed_CM_open_trade,p90_wealth_closed_CM_open_trade,p99_wealth_closed_CM_open_trade,p10_income_closed_CM_open_trade,p50_income_closed_CM_open_trade,p90_income_closed_CM_open_trade,
p99_income_closed_CM_open_trade,p10_cons_closed_CM_open_trade,p50_cons_closed_CM_open_trade,p90_cons_closed_CM_open_trade,p99_cons_closed_CM_open_trade,Aggr_bank_cost_closed_CM_open_trade,mean_leverage_d_closed_CM_open_trade,mean_leverage_x_closed_CM_open_trade,mean_leverage_closed_CM_open_trade,
sd_leverage_d_closed_CM_open_trade,sd_leverage_x_closed_CM_open_trade,sd_leverage_closed_CM_open_trade,corr_MRPK_lev_d_closed_CM_open_trade,corr_MRPK_lev_x_closed_CM_open_trade,corr_MRPK_lev_closed_CM_open_trade,exit_domestic_to_work_sum_closed_CM_open_trade,
exit_exporting_to_work_sum_closed_CM_open_trade,mean_growth_rev_closed_CM_open_trade,sd_growth_rev_closed_CM_open_trade,mean_growth_k_closed_CM_open_trade,sd_growth_k_closed_CM_open_trade,autocorr_rev_closed_CM_open_trade,making_losses_exporter_closed_CM_open_trade,
Misallocation_within_d_closed_CM_open_trade,Misallocation_within_x_closed_CM_open_trade,k_opt_d_fine_closed_CM_open_trade,k_opt_x_fine_closed_CM_open_trade,V_saved_fine_closed_CM_open_trade,avg_rev_xx_entrants_closed_CM_open_trade,NFA_closed_CM_open_trade) = Residual_stst_detailed(prices_closed_CM_open_trade, closed_CM_open_trade_parameter);

#Open capital markets and after trade liberalization
open_CM_open_trade_parameter = copy(Baseline_parameter);
open_CM_open_trade_parameter.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_parameter.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade =  [  0.1615108699987277,
 0.3834834641627776,
 0.15731038567189826,
 2.265224746803689,
 1.369695803751597,
 0.050542885434517466];

(residual_open_CM_open_trade,a_prime_fine_open_CM_open_trade,future_occupation_fine_open_CM_open_trade,cons_fine_open_CM_open_trade,rev_d_fine_store_open_CM_open_trade,
rev_dx_fine_store_open_CM_open_trade,rev_xx_fine_store_open_CM_open_trade,coeff_final_open_CM_open_trade,k_x_fine_open_CM_open_trade,k_d_fine_open_CM_open_trade,
l_x_fine_open_CM_open_trade,l_d_fine_open_CM_open_trade,current_distr_store_open_CM_open_trade,distr_current_open_CM_open_trade,exitflag_open_CM_open_trade,domestic_prod_open_CM_open_trade,exporter_pop_open_CM_open_trade,
domestic_pop_open_CM_open_trade,worker_pop_open_CM_open_trade,entry_share_to_domestic_open_CM_open_trade,exit_share_to_domestic_open_CM_open_trade,
entry_share_to_exporter_open_CM_open_trade,exit_share_to_worker_open_CM_open_trade,total_entry_cost_open_CM_open_trade,
total_incumbents_cost_open_CM_open_trade,total_exit_cost_open_CM_open_trade,labor_excess_demand_open_CM_open_trade,labor_demand_open_CM_open_trade,
total_consumption_open_CM_open_trade,capital_demand_open_CM_open_trade,capital_next_open_CM_open_trade,
total_demand_final_good_open_CM_open_trade,excess_demand_final_good_open_CM_open_trade,GDP_open_CM_open_trade,nomGDP_open_CM_open_trade,PPI_open_CM_open_trade,TFP_open_CM_open_trade,
TFP_within_open_CM_open_trade,TFP_across_open_CM_open_trade,TFP_second_best_open_CM_open_trade,TOT_open_CM_open_trade,TFP_d_open_CM_open_trade,
TFP_d_efficient_open_CM_open_trade,TFP_x_open_CM_open_trade,TFP_x_efficient_open_CM_open_trade,total_production_open_CM_open_trade,
domestic_price_sum_open_CM_open_trade,export_value_open_CM_open_trade,investment_open_CM_open_trade,
L_x_open_CM_open_trade,L_d_open_CM_open_trade,K_x_open_CM_open_trade,K_d_open_CM_open_trade,x_k_open_CM_open_trade,x_l_open_CM_open_trade,D_d_open_CM_open_trade,D_x_open_CM_open_trade,D_d_denom_open_CM_open_trade,D_x_denom_open_CM_open_trade,
D_d_eff_open_CM_open_trade,D_x_eff_open_CM_open_trade,D_d_denom_eff_open_CM_open_trade,D_x_denom_eff_open_CM_open_trade,K_d_ratio_open_CM_open_trade,K_x_ratio_open_CM_open_trade,
L_d_ratio_open_CM_open_trade,L_x_ratio_open_CM_open_trade,K_x_ratio_eff_open_CM_open_trade,K_d_ratio_eff_open_CM_open_trade,L_d_ratio_eff_open_CM_open_trade,
L_x_ratio_eff_open_CM_open_trade,nomGDP_d_open_CM_open_trade,nomGDP_xd_open_CM_open_trade,nomGDP_xx_open_CM_open_trade,RGDP_d_open_CM_open_trade,RGDP_xd_open_CM_open_trade,RGDP_xx_open_CM_open_trade,RGDP_open_CM_open_trade,
mean_MRPK_d_open_CM_open_trade,mean_MRPK_x_open_CM_open_trade,sd_MRPK_d_open_CM_open_trade,sd_MRPK_x_open_CM_open_trade,mean_MRPK_open_CM_open_trade,sd_MRPK_open_CM_open_trade,
mean_MRPL_d_open_CM_open_trade,mean_MRPL_x_open_CM_open_trade,sd_MRPL_d_open_CM_open_trade,sd_MRPL_x_open_CM_open_trade,mean_MRPL_open_CM_open_trade,sd_MRPL_open_CM_open_trade,
cov_TFPR_z_d_open_CM_open_trade,cov_TFPR_z_x_open_CM_open_trade,cov_TFPR_z_open_CM_open_trade,corr_TFPR_z_d_open_CM_open_trade,corr_TFPR_z_x_open_CM_open_trade,
corr_TFPR_z_open_CM_open_trade,mean_logProd_d_open_CM_open_trade,mean_logProd_x_open_CM_open_trade,mean_logProd_open_CM_open_trade,sd_logProd_d_open_CM_open_trade,
sd_logProd_x_open_CM_open_trade,sd_logProd_open_CM_open_trade,import_share_open_CM_open_trade,worker_bond_holding_open_CM_open_trade,
domestic_bond_holding_open_CM_open_trade,exporter_bond_holding_open_CM_open_trade,domestic_firm_debt_open_CM_open_trade,
exporter_firm_debt_open_CM_open_trade,avg_Pi_x_open_CM_open_trade,avg_Pi_d_open_CM_open_trade,Profit_fine_x_open_CM_open_trade,
Profit_fine_d_open_CM_open_trade,mean_cons_open_CM_open_trade,sd_cons_open_CM_open_trade,mean_income_open_CM_open_trade,sd_income_open_CM_open_trade,mean_wealth_open_CM_open_trade,
sd_wealth_open_CM_open_trade,wealth_of_workers_open_CM_open_trade,wealth_of_domestic_open_CM_open_trade,wealth_of_exporters_open_CM_open_trade,
income_of_workers_open_CM_open_trade,income_of_domestic_open_CM_open_trade,income_of_exporters_open_CM_open_trade,
cons_of_workers_open_CM_open_trade,cons_of_domestic_open_CM_open_trade,cons_of_exporters_open_CM_open_trade,GINI_wealth_open_CM_open_trade,
GINI_income_open_CM_open_trade,GINI_cons_open_CM_open_trade,p10_wealth_open_CM_open_trade,p50_wealth_open_CM_open_trade,p90_wealth_open_CM_open_trade,p99_wealth_open_CM_open_trade,p10_income_open_CM_open_trade,p50_income_open_CM_open_trade,p90_income_open_CM_open_trade,
p99_income_open_CM_open_trade,p10_cons_open_CM_open_trade,p50_cons_open_CM_open_trade,p90_cons_open_CM_open_trade,p99_cons_open_CM_open_trade,Aggr_bank_cost_open_CM_open_trade,mean_leverage_d_open_CM_open_trade,mean_leverage_x_open_CM_open_trade,mean_leverage_open_CM_open_trade,
sd_leverage_d_open_CM_open_trade,sd_leverage_x_open_CM_open_trade,sd_leverage_open_CM_open_trade,corr_MRPK_lev_d_open_CM_open_trade,corr_MRPK_lev_x_open_CM_open_trade,corr_MRPK_lev_open_CM_open_trade,exit_domestic_to_work_sum_open_CM_open_trade,
exit_exporting_to_work_sum_open_CM_open_trade,mean_growth_rev_open_CM_open_trade,sd_growth_rev_open_CM_open_trade,mean_growth_k_open_CM_open_trade,sd_growth_k_open_CM_open_trade,autocorr_rev_open_CM_open_trade,making_losses_exporter_open_CM_open_trade,
Misallocation_within_d_open_CM_open_trade,Misallocation_within_x_open_CM_open_trade,k_opt_d_fine_open_CM_open_trade,k_opt_x_fine_open_CM_open_trade,V_saved_fine_open_CM_open_trade ,avg_rev_xx_entrants_open_CM_open_trade,NFA_open_CM_open_trade)= Residual_stst_detailed(prices_open_CM_open_trade, open_CM_open_trade_parameter);
#end
#Open capital markets but no trade liberalization
open_CM_closed_trade_parameter = copy(Baseline_parameter);
open_CM_closed_trade_parameter.openness = 1;

τ_closed_trade = 0.525;
open_CM_closed_trade_parameter.τ = τ_closed_trade * [1.0,1.0];
prices_open_CM_closed_trade =  [   0.15683515778065263,
 0.3814458352482368,
 0.14803931454354882,
 2.305463053708164,
 1.417159358266986,
 0.04915163996012018];

 (residual_open_CM_closed_trade,a_prime_fine_open_CM_closed_trade,future_occupation_fine_open_CM_closed_trade,cons_fine_open_CM_closed_trade,rev_d_fine_store_open_CM_closed_trade,
 rev_dx_fine_store_open_CM_closed_trade,rev_xx_fine_store_open_CM_closed_trade,coeff_final_open_CM_closed_trade,k_x_fine_open_CM_closed_trade,k_d_fine_open_CM_closed_trade,
 l_x_fine_open_CM_closed_trade,l_d_fine_open_CM_closed_trade,current_distr_store_open_CM_closed_trade,distr_current_open_CM_closed_trade,exitflag_open_CM_closed_trade,domestic_prod_open_CM_closed_trade,exporter_pop_open_CM_closed_trade,
 domestic_pop_open_CM_closed_trade,worker_pop_open_CM_closed_trade,entry_share_to_domestic_open_CM_closed_trade,exit_share_to_domestic_open_CM_closed_trade,
 entry_share_to_exporter_open_CM_closed_trade,exit_share_to_worker_open_CM_closed_trade,total_entry_cost_open_CM_closed_trade,
 total_incumbents_cost_open_CM_closed_trade,total_exit_cost_open_CM_closed_trade,labor_excess_demand_open_CM_closed_trade,labor_demand_open_CM_closed_trade,
 total_consumption_open_CM_closed_trade,capital_demand_open_CM_closed_trade,capital_next_open_CM_closed_trade,
 total_demand_final_good_open_CM_closed_trade,excess_demand_final_good_open_CM_closed_trade,GDP_open_CM_closed_trade,nomGDP_open_CM_closed_trade,PPI_open_CM_closed_trade,TFP_open_CM_closed_trade,
 TFP_within_open_CM_closed_trade,TFP_across_open_CM_closed_trade,TFP_second_best_open_CM_closed_trade,TOT_open_CM_closed_trade,TFP_d_open_CM_closed_trade,
 TFP_d_efficient_open_CM_closed_trade,TFP_x_open_CM_closed_trade,TFP_x_efficient_open_CM_closed_trade,total_production_open_CM_closed_trade,
 domestic_price_sum_open_CM_closed_trade,export_value_open_CM_closed_trade,investment_open_CM_closed_trade,
L_x_open_CM_closed_trade,L_d_open_CM_closed_trade,K_x_open_CM_closed_trade,K_d_open_CM_closed_trade,x_k_open_CM_closed_trade,x_l_open_CM_closed_trade,D_d_open_CM_closed_trade,D_x_open_CM_closed_trade,D_d_denom_open_CM_closed_trade,D_x_denom_open_CM_closed_trade,
 D_d_eff_open_CM_closed_trade,D_x_eff_open_CM_closed_trade,D_d_denom_eff_open_CM_closed_trade,D_x_denom_eff_open_CM_closed_trade,K_d_ratio_open_CM_closed_trade,K_x_ratio_open_CM_closed_trade,
 L_d_ratio_open_CM_closed_trade,L_x_ratio_open_CM_closed_trade,K_x_ratio_eff_open_CM_closed_trade,K_d_ratio_eff_open_CM_closed_trade,L_d_ratio_eff_open_CM_closed_trade,
 L_x_ratio_eff_open_CM_closed_trade,nomGDP_d_open_CM_closed_trade,nomGDP_xd_open_CM_closed_trade,nomGDP_xx_open_CM_closed_trade,RGDP_d_open_CM_closed_trade,RGDP_xd_open_CM_closed_trade,RGDP_xx_open_CM_closed_trade,RGDP_open_CM_closed_trade,
 mean_MRPK_d_open_CM_closed_trade,mean_MRPK_x_open_CM_closed_trade,sd_MRPK_d_open_CM_closed_trade,sd_MRPK_x_open_CM_closed_trade,mean_MRPK_open_CM_closed_trade,sd_MRPK_open_CM_closed_trade,
 mean_MRPL_d_open_CM_closed_trade,mean_MRPL_x_open_CM_closed_trade,sd_MRPL_d_open_CM_closed_trade,sd_MRPL_x_open_CM_closed_trade,mean_MRPL_open_CM_closed_trade,sd_MRPL_open_CM_closed_trade,
 cov_TFPR_z_d_open_CM_closed_trade,cov_TFPR_z_x_open_CM_closed_trade,cov_TFPR_z_open_CM_closed_trade,corr_TFPR_z_d_open_CM_closed_trade,corr_TFPR_z_x_open_CM_closed_trade,
 corr_TFPR_z_open_CM_closed_trade,mean_logProd_d_open_CM_closed_trade,mean_logProd_x_open_CM_closed_trade,mean_logProd_open_CM_closed_trade,sd_logProd_d_open_CM_closed_trade,
 sd_logProd_x_open_CM_closed_trade,sd_logProd_open_CM_closed_trade,import_share_open_CM_closed_trade,worker_bond_holding_open_CM_closed_trade,
 domestic_bond_holding_open_CM_closed_trade,exporter_bond_holding_open_CM_closed_trade,domestic_firm_debt_open_CM_closed_trade,
 exporter_firm_debt_open_CM_closed_trade,avg_Pi_x_open_CM_closed_trade,avg_Pi_d_open_CM_closed_trade,Profit_fine_x_open_CM_closed_trade,
 Profit_fine_d_open_CM_closed_trade,mean_cons_open_CM_closed_trade,sd_cons_open_CM_closed_trade,mean_income_open_CM_closed_trade,sd_income_open_CM_closed_trade,mean_wealth_open_CM_closed_trade,
 sd_wealth_open_CM_closed_trade,wealth_of_workers_open_CM_closed_trade,wealth_of_domestic_open_CM_closed_trade,wealth_of_exporters_open_CM_closed_trade,
 income_of_workers_open_CM_closed_trade,income_of_domestic_open_CM_closed_trade,income_of_exporters_open_CM_closed_trade,
 cons_of_workers_open_CM_closed_trade,cons_of_domestic_open_CM_closed_trade,cons_of_exporters_open_CM_closed_trade,GINI_wealth_open_CM_closed_trade,
 GINI_income_open_CM_closed_trade,GINI_cons_open_CM_closed_trade,p10_wealth_open_CM_closed_trade,p50_wealth_open_CM_closed_trade,p90_wealth_open_CM_closed_trade,p99_wealth_open_CM_closed_trade,p10_income_open_CM_closed_trade,p50_income_open_CM_closed_trade,p90_income_open_CM_closed_trade,
 p99_income_open_CM_closed_trade,p10_cons_open_CM_closed_trade,p50_cons_open_CM_closed_trade,p90_cons_open_CM_closed_trade,p99_cons_open_CM_closed_trade,Aggr_bank_cost_open_CM_closed_trade,mean_leverage_d_open_CM_closed_trade,mean_leverage_x_open_CM_closed_trade,mean_leverage_open_CM_closed_trade,
 sd_leverage_d_open_CM_closed_trade,sd_leverage_x_open_CM_closed_trade,sd_leverage_open_CM_closed_trade,corr_MRPK_lev_d_open_CM_closed_trade,corr_MRPK_lev_x_open_CM_closed_trade,corr_MRPK_lev_open_CM_closed_trade,exit_domestic_to_work_sum_open_CM_closed_trade,
 exit_exporting_to_work_sum_open_CM_closed_trade,mean_growth_rev_open_CM_closed_trade,sd_growth_rev_open_CM_closed_trade,mean_growth_k_open_CM_closed_trade,sd_growth_k_open_CM_closed_trade,autocorr_rev_open_CM_closed_trade,making_losses_exporter_open_CM_closed_trade,
 Misallocation_within_d_open_CM_closed_trade,Misallocation_within_x_open_CM_closed_trade,k_opt_d_fine_open_CM_closed_trade,k_opt_x_fine_open_CM_closed_trade,V_saved_fine_open_CM_closed_trade,avg_rev_xx_entrants_open_CM_closed_trade,NFA_open_CM_closed_trade) = Residual_stst_detailed(prices_open_CM_closed_trade, open_CM_closed_trade_parameter);

#end
