include("code_new.jl")
#using Plotly

#@everywhere begin
#Pre - trade liberalization
prices_initial = [     0.1548780916238482,
 0.37764334656717075,
 0.14285239632185193,
 2.2354478711937644,
 1.3967375057493472,
 0.13592297418118138,
 0.049066966707359445];

τ_closed_trade = 0.525; #Final bilateral low tariff state
Baseline_parameter.τ = τ_closed_trade * [1.0,1.0];

(residual_initial,a_prime_fine_initial,future_occupation_fine_initial,cons_fine_initial,rev_d_fine_store_initial,
rev_dx_fine_store_initial,rev_xx_fine_store_initial,coeff_final_initial,k_x_fine_initial,k_d_fine_initial,
l_x_fine_initial,l_d_fine_initial,current_distr_store_initial,distr_current_initial,exitflag_initial,domestic_prod_initial,exporter_pop_initial,
domestic_pop_initial,worker_pop_initial,entry_share_to_domestic_initial,exit_share_to_domestic_initial,
entry_share_to_exporter_initial,exit_share_to_worker_initial,total_entry_cost_initial,
total_incumbents_cost_initial,total_exit_cost_initial,labor_excess_demand_initial,labor_demand_initial,
total_consumption_initial,capital_demand_initial,capital_next_initial,
total_demand_final_good_initial,excess_demand_final_good_initial,GDP_initial,nomGDP_initial,PPI_initial,TFP_initial,
TFP_within_initial,TFP_across_initial,TFP_second_best_initial,TOT_initial,TFP_d_initial,
TFP_d_efficient_initial,TFP_x_initial,TFP_x_efficient_initial,total_production_initial,
domestic_price_sum_initial,export_value_initial,investment_initial,
export_value_initial,L_x_initial,L_d_initial,K_x_initial,K_d_initial,x_k_initial,x_l_initial,D_d_initial,D_x_initial,D_d_denom_initial,D_x_denom_initial,
D_d_eff_initial,D_x_eff_initial,D_d_denom_eff_initial,D_x_denom_eff_initial,K_d_ratio_initial,K_x_ratio_initial,
L_d_ratio_initial,L_x_ratio_initial,K_x_ratio_eff_initial,K_d_ratio_eff_initial,L_d_ratio_eff_initial,
L_x_ratio_eff_initial,nomGDP_d_initial,nomGDP_xd_initial,nomGDP_xx_initial,RGDP_d_initial,RGDP_xd_initial,RGDP_xx_initial,RGDP_initial,
mean_MRPK_d_initial,mean_MRPK_x_initial,sd_MRPK_d_initial,sd_MRPK_x_initial,mean_MRPK_initial,sd_MRPK_initial,
mean_MRPL_d_initial,mean_MRPL_x_initial,sd_MRPL_d_initial,sd_MRPL_x_initial,mean_MRPL_initial,sd_MRPL_initial,
cov_TFPR_z_d_initial,cov_TFPR_z_x_initial,cov_TFPR_z_initial,corr_TFPR_z_d_initial,corr_TFPR_z_x_initial,
corr_TFPR_z_initial,mean_logProd_d_initial,mean_logProd_x_initial,mean_logProd_initial,sd_logProd_d_initial,
sd_logProd_x_initial,sd_logProd_initial,import_share_initial,worker_bond_holding_initial,
domestic_bond_holding_initial,exporter_bond_holding_initial,domestic_firm_debt_initial,
exporter_firm_debt_initial,avg_Pi_x_initial,avg_Pi_d_initial,Profit_fine_x_initial,
Profit_fine_d_initial,mean_cons_initial,sd_cons_initial,mean_income_initial,sd_income_initial,mean_wealth_initial,
sd_wealth_initial,wealth_of_workers_initial,wealth_of_domestic_initial,wealth_of_exporters_initial,
income_of_workers_initial,income_of_domestic_initial,income_of_exporters_initial,
cons_of_workers_initial,cons_of_domestic_initial,cons_of_exporters_initial,GINI_wealth_initial,
GINI_income_initial,GINI_cons_initial,p10_wealth_initial,p50_wealth_initial,p90_wealth_initial,p99_wealth_initial,p10_income_initial,p50_income_initial,p90_income_initial,
p99_income_initial,p10_cons_initial,p50_cons_initial,p90_cons_initial,p99_cons_initial,Aggr_bank_cost_initial,mean_leverage_d_initial,mean_leverage_x_initial,mean_leverage_initial,
sd_leverage_d_initial,sd_leverage_x_initial,sd_leverage_initial,corr_MRPK_lev_d_initial,corr_MRPK_lev_x_initial,corr_MRPK_lev_initial,exit_domestic_to_work_sum_initial,
exit_exporting_to_work_sum_initial,mean_growth_rev_initial,sd_growth_rev_initial,mean_growth_k_initial,sd_growth_k_initial,autocorr_rev_initial,
fraction_zombie_exporter_initial,Misallocation_within_d_initial,Misallocation_within_x_initial,k_opt_d_fine_initial,k_opt_x_fine_initial) = Residual_stst_detailed(prices_initial, Baseline_parameter);

#Closed capital markets and after trade liberalization
closed_CM_open_trade_parameter = copy(Baseline_parameter);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_parameter.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade = [  0.15736639937663147,
0.3697983186132166,
0.15759877959397917,
2.0449626046287253,
1.3252338424810661,
0.13667508873036238,
0.050308422000531754];

(residual_closed_CM_open_trade,a_prime_fine_closed_CM_open_trade,future_occupation_fine_closed_CM_open_trade,cons_fine_closed_CM_open_trade,rev_d_fine_store_closed_CM_open_trade,
rev_dx_fine_store_closed_CM_open_trade,rev_xx_fine_store_closed_CM_open_trade,coeff_final_closed_CM_open_trade,k_x_fine_closed_CM_open_trade,k_d_fine_closed_CM_open_trade,
l_x_fine_closed_CM_open_trade,l_d_fine_closed_CM_open_trade,current_distr_store_closed_CM_open_trade,distr_current_closed_CM_open_trade,exitflag_closed_CM_open_trade,domestic_prod_closed_CM_open_trade,exporter_pop_closed_CM_open_trade,
domestic_pop_closed_CM_open_trade,worker_pop_closed_CM_open_trade,entry_share_to_domestic_closed_CM_open_trade,exit_share_to_domestic_closed_CM_open_trade,
entry_share_to_exporter_closed_CM_open_trade,exit_share_to_worker_closed_CM_open_trade,total_entry_cost_closed_CM_open_trade,
total_incumbents_cost_closed_CM_open_trade,total_exit_cost_closed_CM_open_trade,labor_excess_demand_closed_CM_open_trade,labor_demand_closed_CM_open_trade,
total_consumption_closed_CM_open_trade,capital_demand_closed_CM_open_trade,capital_next_closed_CM_open_trade,
total_demand_final_good_closed_CM_open_trade,excess_demand_final_good_closed_CM_open_trade,GDP_closed_CM_open_trade,nomGDP_closed_CM_open_trade,PPI_closed_CM_open_trade,TFP_closed_CM_open_trade,
TFP_within_closed_CM_open_trade,TFP_across_closed_CM_open_trade,TFP_second_best_closed_CM_open_trade,TOT_closed_CM_open_trade,TFP_d_closed_CM_open_trade,
TFP_d_efficient_closed_CM_open_trade,TFP_x_closed_CM_open_trade,TFP_x_efficient_closed_CM_open_trade,total_production_closed_CM_open_trade,
domestic_price_sum_closed_CM_open_trade,export_value_closed_CM_open_trade,investment_closed_CM_open_trade,
export_value_closed_CM_open_trade,L_x_closed_CM_open_trade,L_d_closed_CM_open_trade,K_x_closed_CM_open_trade,K_d_closed_CM_open_trade,x_k_closed_CM_open_trade,x_l_closed_CM_open_trade,D_d_closed_CM_open_trade,D_x_closed_CM_open_trade,D_d_denom_closed_CM_open_trade,D_x_denom_closed_CM_open_trade,
D_d_eff_closed_CM_open_trade,D_x_eff_closed_CM_open_trade,D_d_denom_eff_closed_CM_open_trade,D_x_denom_eff_closed_CM_open_trade,K_d_ratio_closed_CM_open_trade,K_x_ratio_closed_CM_open_trade,
L_d_ratio_closed_CM_open_trade,L_x_ratio_closed_CM_open_trade,K_x_ratio_eff_closed_CM_open_trade,K_d_ratio_eff_closed_CM_open_trade,L_d_ratio_eff_closed_CM_open_trade,
L_x_ratio_eff_closed_CM_open_trade,nomGDP_d_closed_CM_open_trade,nomGDP_xd_closed_CM_open_trade,nomGDP_xx_closed_CM_open_trade,RGDP_d_closed_CM_open_trade,RGDP_xd_closed_CM_open_trade,RGDP_xx_closed_CM_open_trade,RGDP_closed_CM_open_trade,
mean_MRPK_d_closed_CM_open_trade,mean_MRPK_x_closed_CM_open_trade,sd_MRPK_d_closed_CM_open_trade,sd_MRPK_x_closed_CM_open_trade,mean_MRPK_closed_CM_open_trade,sd_MRPK_closed_CM_open_trade,
mean_MRPL_d_closed_CM_open_trade,mean_MRPL_x_closed_CM_open_trade,sd_MRPL_d_closed_CM_open_trade,sd_MRPL_x_closed_CM_open_trade,mean_MRPL_closed_CM_open_trade,sd_MRPL_closed_CM_open_trade,
cov_TFPR_z_d_closed_CM_open_trade,cov_TFPR_z_x_closed_CM_open_trade,cov_TFPR_z_closed_CM_open_trade,corr_TFPR_z_d_closed_CM_open_trade,corr_TFPR_z_x_closed_CM_open_trade,
corr_TFPR_z_closed_CM_open_trade,mean_logProd_d_closed_CM_open_trade,mean_logProd_x_closed_CM_open_trade,mean_logProd_closed_CM_open_trade,sd_logProd_d_closed_CM_open_trade,
sd_logProd_x_closed_CM_open_trade,sd_logProd_closed_CM_open_trade,import_share_closed_CM_open_trade,worker_bond_holding_closed_CM_open_trade,
domestic_bond_holding_closed_CM_open_trade,exporter_bond_holding_closed_CM_open_trade,domestic_firm_debt_closed_CM_open_trade,
exporter_firm_debt_closed_CM_open_trade,avg_Pi_x_closed_CM_open_trade,avg_Pi_d_closed_CM_open_trade,Profit_fine_x_closed_CM_open_trade,
Profit_fine_d_closed_CM_open_trade,mean_cons_closed_CM_open_trade,sd_cons_closed_CM_open_trade,mean_income_closed_CM_open_trade,sd_income_closed_CM_open_trade,mean_wealth_closed_CM_open_trade,
sd_wealth_closed_CM_open_trade,wealth_of_workers_closed_CM_open_trade,wealth_of_domestic_closed_CM_open_trade,wealth_of_exporters_closed_CM_open_trade,
income_of_workers_closed_CM_open_trade,income_of_domestic_closed_CM_open_trade,income_of_exporters_closed_CM_open_trade,
cons_of_workers_closed_CM_open_trade,cons_of_domestic_closed_CM_open_trade,cons_of_exporters_closed_CM_open_trade,GINI_wealth_closed_CM_open_trade,
GINI_income_closed_CM_open_trade,GINI_cons_closed_CM_open_trade,p10_wealth_closed_CM_open_trade,p50_wealth_closed_CM_open_trade,p90_wealth_closed_CM_open_trade,p99_wealth_closed_CM_open_trade,p10_income_closed_CM_open_trade,p50_income_closed_CM_open_trade,p90_income_closed_CM_open_trade,
p99_income_closed_CM_open_trade,p10_cons_closed_CM_open_trade,p50_cons_closed_CM_open_trade,p90_cons_closed_CM_open_trade,p99_cons_closed_CM_open_trade,Aggr_bank_cost_closed_CM_open_trade,mean_leverage_d_closed_CM_open_trade,mean_leverage_x_closed_CM_open_trade,mean_leverage_closed_CM_open_trade,
sd_leverage_d_closed_CM_open_trade,sd_leverage_x_closed_CM_open_trade,sd_leverage_closed_CM_open_trade,corr_MRPK_lev_d_closed_CM_open_trade,corr_MRPK_lev_x_closed_CM_open_trade,corr_MRPK_lev_closed_CM_open_trade,exit_domestic_to_work_sum_closed_CM_open_trade,
exit_exporting_to_work_sum_closed_CM_open_trade,mean_growth_rev_closed_CM_open_trade,sd_growth_rev_closed_CM_open_trade,mean_growth_k_closed_CM_open_trade,sd_growth_k_closed_CM_open_trade,autocorr_rev_closed_CM_open_trade,fraction_zombie_exporter_closed_CM_open_trade,
Misallocation_within_d_closed_CM_open_trade,Misallocation_within_x_closed_CM_open_trade,k_opt_d_fine_closed_CM_open_trade,k_opt_x_fine_closed_CM_open_trade) = Residual_stst_detailed(prices_closed_CM_open_trade, closed_CM_open_trade_parameter);

#Open capital markets and after trade liberalization
open_CM_open_trade_parameter = copy(Baseline_parameter);
open_CM_open_trade_parameter.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_parameter.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade =  [ 0.16151136157660906,
0.3834759828492296,
0.15729067146766804,
2.2652287780008287,
1.3696986792605672,
0.05054456076806949];

(residual_open_CM_open_trade,a_prime_fine_open_CM_open_trade,future_occupation_fine_open_CM_open_trade,cons_fine_open_CM_open_trade,rev_d_fine_store_open_CM_open_trade,
rev_dx_fine_store_open_CM_open_trade,rev_xx_fine_store_open_CM_open_trade,coeff_final_open_CM_open_trade,k_x_fine_open_CM_open_trade,k_d_fine_open_CM_open_trade,
l_x_fine_open_CM_open_trade,l_d_fine_open_CM_open_trade,current_distr_store_open_CM_open_trade,distr_current_open_CM_open_trade,exitflag_open_CM_open_trade,domestic_prod_open_CM_open_trade,exporter_pop_open_CM_open_trade,
domestic_pop_open_CM_open_trade,worker_pop_open_CM_open_trade,entry_share_to_domestic_open_CM_open_trade,exit_share_to_domestic_open_CM_open_trade,
entry_share_to_exporter_open_CM_open_trade,exit_share_to_worker_open_CM_open_trade,total_entry_cost_open_CM_open_trade,
total_incumbents_cost_open_CM_open_trade,total_exit_cost_open_CM_open_trade,labor_excess_demand_open_CM_open_trade,labor_demand_open_CM_open_trade,
total_consumption_open_CM_open_trade,capital_demand_open_CM_open_trade,capital_next_open_CM_open_trade,
total_demand_final_good_open_CM_open_trade,excess_demand_final_good_open_CM_open_trade,GDP_open_CM_open_trade,nomGDP_open_CM_open_trade,PPI_open_CM_open_trade,TFP_open_CM_open_trade,
TFP_within_open_CM_open_trade,TFP_across_open_CM_open_trade,TFP_second_best_open_CM_open_trade,TOT_open_CM_open_trade,TFP_d_open_CM_open_trade,
TFP_d_efficient_open_CM_open_trade,TFP_x_open_CM_open_trade,TFP_x_efficient_open_CM_open_trade,total_production_open_CM_open_trade,
domestic_price_sum_open_CM_open_trade,export_value_open_CM_open_trade,investment_open_CM_open_trade,
export_value_open_CM_open_trade,L_x_open_CM_open_trade,L_d_open_CM_open_trade,K_x_open_CM_open_trade,K_d_open_CM_open_trade,x_k_open_CM_open_trade,x_l_open_CM_open_trade,D_d_open_CM_open_trade,D_x_open_CM_open_trade,D_d_denom_open_CM_open_trade,D_x_denom_open_CM_open_trade,
D_d_eff_open_CM_open_trade,D_x_eff_open_CM_open_trade,D_d_denom_eff_open_CM_open_trade,D_x_denom_eff_open_CM_open_trade,K_d_ratio_open_CM_open_trade,K_x_ratio_open_CM_open_trade,
L_d_ratio_open_CM_open_trade,L_x_ratio_open_CM_open_trade,K_x_ratio_eff_open_CM_open_trade,K_d_ratio_eff_open_CM_open_trade,L_d_ratio_eff_open_CM_open_trade,
L_x_ratio_eff_open_CM_open_trade,nomGDP_d_open_CM_open_trade,nomGDP_xd_open_CM_open_trade,nomGDP_xx_open_CM_open_trade,RGDP_d_open_CM_open_trade,RGDP_xd_open_CM_open_trade,RGDP_xx_open_CM_open_trade,RGDP_open_CM_open_trade,
mean_MRPK_d_open_CM_open_trade,mean_MRPK_x_open_CM_open_trade,sd_MRPK_d_open_CM_open_trade,sd_MRPK_x_open_CM_open_trade,mean_MRPK_open_CM_open_trade,sd_MRPK_open_CM_open_trade,
mean_MRPL_d_open_CM_open_trade,mean_MRPL_x_open_CM_open_trade,sd_MRPL_d_open_CM_open_trade,sd_MRPL_x_open_CM_open_trade,mean_MRPL_open_CM_open_trade,sd_MRPL_open_CM_open_trade,
cov_TFPR_z_d_open_CM_open_trade,cov_TFPR_z_x_open_CM_open_trade,cov_TFPR_z_open_CM_open_trade,corr_TFPR_z_d_open_CM_open_trade,corr_TFPR_z_x_open_CM_open_trade,
corr_TFPR_z_open_CM_open_trade,mean_logProd_d_open_CM_open_trade,mean_logProd_x_open_CM_open_trade,mean_logProd_open_CM_open_trade,sd_logProd_d_open_CM_open_trade,
sd_logProd_x_open_CM_open_trade,sd_logProd_open_CM_open_trade,import_share_open_CM_open_trade,worker_bond_holding_open_CM_open_trade,
domestic_bond_holding_open_CM_open_trade,exporter_bond_holding_open_CM_open_trade,domestic_firm_debt_open_CM_open_trade,
exporter_firm_debt_open_CM_open_trade,avg_Pi_x_open_CM_open_trade,avg_Pi_d_open_CM_open_trade,Profit_fine_x_open_CM_open_trade,
Profit_fine_d_open_CM_open_trade,mean_cons_open_CM_open_trade,sd_cons_open_CM_open_trade,mean_income_open_CM_open_trade,sd_income_open_CM_open_trade,mean_wealth_open_CM_open_trade,
sd_wealth_open_CM_open_trade,wealth_of_workers_open_CM_open_trade,wealth_of_domestic_open_CM_open_trade,wealth_of_exporters_open_CM_open_trade,
income_of_workers_open_CM_open_trade,income_of_domestic_open_CM_open_trade,income_of_exporters_open_CM_open_trade,
cons_of_workers_open_CM_open_trade,cons_of_domestic_open_CM_open_trade,cons_of_exporters_open_CM_open_trade,GINI_wealth_open_CM_open_trade,
GINI_income_open_CM_open_trade,GINI_cons_open_CM_open_trade,p10_wealth_open_CM_open_trade,p50_wealth_open_CM_open_trade,p90_wealth_open_CM_open_trade,p99_wealth_open_CM_open_trade,p10_income_open_CM_open_trade,p50_income_open_CM_open_trade,p90_income_open_CM_open_trade,
p99_income_open_CM_open_trade,p10_cons_open_CM_open_trade,p50_cons_open_CM_open_trade,p90_cons_open_CM_open_trade,p99_cons_open_CM_open_trade,Aggr_bank_cost_open_CM_open_trade,mean_leverage_d_open_CM_open_trade,mean_leverage_x_open_CM_open_trade,mean_leverage_open_CM_open_trade,
sd_leverage_d_open_CM_open_trade,sd_leverage_x_open_CM_open_trade,sd_leverage_open_CM_open_trade,corr_MRPK_lev_d_open_CM_open_trade,corr_MRPK_lev_x_open_CM_open_trade,corr_MRPK_lev_open_CM_open_trade,exit_domestic_to_work_sum_open_CM_open_trade,
exit_exporting_to_work_sum_open_CM_open_trade,mean_growth_rev_open_CM_open_trade,sd_growth_rev_open_CM_open_trade,mean_growth_k_open_CM_open_trade,sd_growth_k_open_CM_open_trade,autocorr_rev_open_CM_open_trade,fraction_zombie_exporter_open_CM_open_trade,
Misallocation_within_d_open_CM_open_trade,Misallocation_within_x_open_CM_open_trade,k_opt_d_fine_open_CM_open_trade,k_opt_x_fine_open_CM_open_trade) = Residual_stst_detailed(prices_open_CM_open_trade, open_CM_open_trade_parameter);
#end
#Open capital markets but no trade liberalization
open_CM_closed_trade_parameter = copy(Baseline_parameter);
open_CM_closed_trade_parameter.openness = 1;

τ_closed_trade = 0.525;
open_CM_closed_trade_parameter.τ = τ_closed_trade * [1.0,1.0];
prices_open_CM_closed_trade =  [  0.1570373758537133,
 0.3814381504749829,
 0.14864104917615595,
 2.305629356099255,
 1.4177476852042976,
 0.04916613677513132];

 (residual_open_CM_closed_trade,a_prime_fine_open_CM_closed_trade,future_occupation_fine_open_CM_closed_trade,cons_fine_open_CM_closed_trade,rev_d_fine_store_open_CM_closed_trade,
 rev_dx_fine_store_open_CM_closed_trade,rev_xx_fine_store_open_CM_closed_trade,coeff_final_open_CM_closed_trade,k_x_fine_open_CM_closed_trade,k_d_fine_open_CM_closed_trade,
 l_x_fine_open_CM_closed_trade,l_d_fine_open_CM_closed_trade,current_distr_store_open_CM_closed_trade,distr_current_open_CM_closed_trade,exitflag_open_CM_closed_trade,domestic_prod_open_CM_closed_trade,exporter_pop_open_CM_closed_trade,
 domestic_pop_open_CM_closed_trade,worker_pop_open_CM_closed_trade,entry_share_to_domestic_open_CM_closed_trade,exit_share_to_domestic_open_CM_closed_trade,
 entry_share_to_exporter_open_CM_closed_trade,exit_share_to_worker_open_CM_closed_trade,total_entry_cost_open_CM_closed_trade,
 total_incumbents_cost_open_CM_closed_trade,total_exit_cost_open_CM_closed_trade,labor_excess_demand_open_CM_closed_trade,labor_demand_open_CM_closed_trade,
 total_consumption_open_CM_closed_trade,capital_demand_open_CM_closed_trade,capital_next_open_CM_closed_trade,
 total_demand_final_good_open_CM_closed_trade,excess_demand_final_good_open_CM_closed_trade,GDP_open_CM_closed_trade,nomGDP_open_CM_closed_trade,PPI_open_CM_closed_trade,TFP_open_CM_closed_trade,
 TFP_within_open_CM_closed_trade,TFP_across_open_CM_closed_trade,TFP_second_best_open_CM_closed_trade,TOT_open_CM_closed_trade,TFP_d_open_CM_closed_trade,
 TFP_d_efficient_open_CM_closed_trade,TFP_x_open_CM_closed_trade,TFP_x_efficient_open_CM_closed_trade,total_production_open_CM_closed_trade,
 domestic_price_sum_open_CM_closed_trade,export_value_open_CM_closed_trade,investment_open_CM_closed_trade,
 export_value_open_CM_closed_trade,L_x_open_CM_closed_trade,L_d_open_CM_closed_trade,K_x_open_CM_closed_trade,K_d_open_CM_closed_trade,x_k_open_CM_closed_trade,x_l_open_CM_closed_trade,D_d_open_CM_closed_trade,D_x_open_CM_closed_trade,D_d_denom_open_CM_closed_trade,D_x_denom_open_CM_closed_trade,
 D_d_eff_open_CM_closed_trade,D_x_eff_open_CM_closed_trade,D_d_denom_eff_open_CM_closed_trade,D_x_denom_eff_open_CM_closed_trade,K_d_ratio_open_CM_closed_trade,K_x_ratio_open_CM_closed_trade,
 L_d_ratio_open_CM_closed_trade,L_x_ratio_open_CM_closed_trade,K_x_ratio_eff_open_CM_closed_trade,K_d_ratio_eff_open_CM_closed_trade,L_d_ratio_eff_open_CM_closed_trade,
 L_x_ratio_eff_open_CM_closed_trade,nomGDP_d_open_CM_closed_trade,nomGDP_xd_open_CM_closed_trade,nomGDP_xx_open_CM_closed_trade,RGDP_d_open_CM_closed_trade,RGDP_xd_open_CM_closed_trade,RGDP_xx_open_CM_closed_trade,RGDP_open_CM_closed_trade,
 mean_MRPK_d_open_CM_closed_trade,mean_MRPK_x_open_CM_closed_trade,sd_MRPK_d_open_CM_closed_trade,sd_MRPK_x_open_CM_closed_trade,mean_MRPK_open_CM_closed_trade,sd_MRPK_open_CM_closed_trade,
 mean_MRPL_d_open_CM_closed_trade,mean_MRPL_x_open_CM_closed_trade,sd_MRPL_d_open_CM_closed_trade,sd_MRPL_x_open_CM_closed_trade,mean_MRPL_open_CM_closed_trade,sd_MRPL_open_CM_closed_trade,
 cov_TFPR_z_d_open_CM_closed_trade,cov_TFPR_z_x_open_CM_closed_trade,cov_TFPR_z_open_CM_closed_trade,corr_TFPR_z_d_open_CM_closed_trade,corr_TFPR_z_x_open_CM_closed_trade,
 corr_TFPR_z_open_CM_closed_trade,mean_logProd_d_open_CM_closed_trade,mean_logProd_x_open_CM_closed_trade,mean_logProd_open_CM_closed_trade,sd_logProd_d_open_CM_closed_trade,
 sd_logProd_x_open_CM_closed_trade,sd_logProd_open_CM_closed_trade,import_share_open_CM_closed_trade,worker_bond_holding_open_CM_closed_trade,
 domestic_bond_holding_open_CM_closed_trade,exporter_bond_holding_open_CM_closed_trade,domestic_firm_debt_open_CM_closed_trade,
 exporter_firm_debt_open_CM_closed_trade,avg_Pi_x_open_CM_closed_trade,avg_Pi_d_open_CM_closed_trade,Profit_fine_x_open_CM_closed_trade,
 Profit_fine_d_open_CM_closed_trade,mean_cons_open_CM_closed_trade,sd_cons_open_CM_closed_trade,mean_income_open_CM_closed_trade,sd_income_open_CM_closed_trade,mean_wealth_open_CM_closed_trade,
 sd_wealth_open_CM_closed_trade,wealth_of_workers_open_CM_closed_trade,wealth_of_domestic_open_CM_closed_trade,wealth_of_exporters_open_CM_closed_trade,
 income_of_workers_open_CM_closed_trade,income_of_domestic_open_CM_closed_trade,income_of_exporters_open_CM_closed_trade,
 cons_of_workers_open_CM_closed_trade,cons_of_domestic_open_CM_closed_trade,cons_of_exporters_open_CM_closed_trade,GINI_wealth_open_CM_closed_trade,
 GINI_income_open_CM_closed_trade,GINI_cons_open_CM_closed_trade,p10_wealth_open_CM_closed_trade,p50_wealth_open_CM_closed_trade,p90_wealth_open_CM_closed_trade,p99_wealth_open_CM_closed_trade,p10_income_open_CM_closed_trade,p50_income_open_CM_closed_trade,p90_income_open_CM_closed_trade,
 p99_income_open_CM_closed_trade,p10_cons_open_CM_closed_trade,p50_cons_open_CM_closed_trade,p90_cons_open_CM_closed_trade,p99_cons_open_CM_closed_trade,Aggr_bank_cost_open_CM_closed_trade,mean_leverage_d_open_CM_closed_trade,mean_leverage_x_open_CM_closed_trade,mean_leverage_open_CM_closed_trade,
 sd_leverage_d_open_CM_closed_trade,sd_leverage_x_open_CM_closed_trade,sd_leverage_open_CM_closed_trade,corr_MRPK_lev_d_open_CM_closed_trade,corr_MRPK_lev_x_open_CM_closed_trade,corr_MRPK_lev_open_CM_closed_trade,exit_domestic_to_work_sum_open_CM_closed_trade,
 exit_exporting_to_work_sum_open_CM_closed_trade,mean_growth_rev_open_CM_closed_trade,sd_growth_rev_open_CM_closed_trade,mean_growth_k_open_CM_closed_trade,sd_growth_k_open_CM_closed_trade,autocorr_rev_open_CM_closed_trade,fraction_zombie_exporter_open_CM_closed_trade,
 Misallocation_within_d_open_CM_closed_trade,Misallocation_within_x_open_CM_closed_trade,k_opt_d_fine_open_CM_closed_trade,k_opt_x_fine_open_CM_closed_trade) = Residual_stst_detailed(prices_open_CM_closed_trade, open_CM_closed_trade_parameter);

# Economies with higher development (beta and theta)
#Pre - trade liberalization
Developed_parameter = copy(Baseline_parameter);
prices_initial_dev = [     0.24161989732597744,
 0.3802642106883798,
 0.22359291702376602,
 2.2793541460987874,
 1.2917589472420485,
 0.05657348796240367,
 0.04927883694602443];
Developed_parameter.β[1] = 0.948;
Developed_parameter.θ[1] = 0.86;
τ_closed_trade = 0.525; #Final bilateral low tariff state
Developed_parameter.τ = τ_closed_trade * [1.0,1.0];

(residual_initial_dev,a_prime_fine_initial_dev,future_occupation_fine_initial_dev,cons_fine_initial_dev,rev_d_fine_store_initial_dev,
rev_dx_fine_store_initial_dev,rev_xx_fine_store_initial_dev,coeff_final_initial_dev,k_x_fine_initial_dev,k_d_fine_initial_dev,
l_x_fine_initial_dev,l_d_fine_initial_dev,current_distr_store_initial_dev,distr_current_initial_dev,exitflag_initial_dev,domestic_prod_initial_dev,exporter_pop_initial_dev,
domestic_pop_initial_dev,worker_pop_initial_dev,entry_share_to_domestic_initial_dev,exit_share_to_domestic_initial_dev,
entry_share_to_exporter_initial_dev,exit_share_to_worker_initial_dev,total_entry_cost_initial_dev,
total_incumbents_cost_initial_dev,total_exit_cost_initial_dev,labor_excess_demand_initial_dev,labor_demand_initial_dev,
total_consumption_initial_dev,capital_demand_initial_dev,capital_next_initial_dev,
total_demand_final_good_initial_dev,excess_demand_final_good_initial_dev,GDP_initial_dev,nomGDP_initial_dev,PPI_initial_dev,TFP_initial_dev,
TFP_within_initial_dev,TFP_across_initial_dev,TFP_second_best_initial_dev,TOT_initial_dev,TFP_d_initial_dev,
TFP_d_efficient_initial_dev,TFP_x_initial_dev,TFP_x_efficient_initial_dev,total_production_initial_dev,
domestic_price_sum_initial_dev,export_value_initial_dev,investment_initial_dev,
export_value_initial_dev,L_x_initial_dev,L_d_initial_dev,K_x_initial_dev,K_d_initial_dev,x_k_initial_dev,x_l_initial_dev,D_d_initial_dev,D_x_initial_dev,D_d_denom_initial_dev,D_x_denom_initial_dev,
D_d_eff_initial_dev,D_x_eff_initial_dev,D_d_denom_eff_initial_dev,D_x_denom_eff_initial_dev,K_d_ratio_initial_dev,K_x_ratio_initial_dev,
L_d_ratio_initial_dev,L_x_ratio_initial_dev,K_x_ratio_eff_initial_dev,K_d_ratio_eff_initial_dev,L_d_ratio_eff_initial_dev,
L_x_ratio_eff_initial_dev,nomGDP_d_initial_dev,nomGDP_xd_initial_dev,nomGDP_xx_initial_dev,RGDP_d_initial_dev,RGDP_xd_initial_dev,RGDP_xx_initial_dev,RGDP_initial_dev,
mean_MRPK_d_initial_dev,mean_MRPK_x_initial_dev,sd_MRPK_d_initial_dev,sd_MRPK_x_initial_dev,mean_MRPK_initial_dev,sd_MRPK_initial_dev,
mean_MRPL_d_initial_dev,mean_MRPL_x_initial_dev,sd_MRPL_d_initial_dev,sd_MRPL_x_initial_dev,mean_MRPL_initial_dev,sd_MRPL_initial_dev,
cov_TFPR_z_d_initial_dev,cov_TFPR_z_x_initial_dev,cov_TFPR_z_initial_dev,corr_TFPR_z_d_initial_dev,corr_TFPR_z_x_initial_dev,
corr_TFPR_z_initial_dev,mean_logProd_d_initial_dev,mean_logProd_x_initial_dev,mean_logProd_initial_dev,sd_logProd_d_initial_dev,
sd_logProd_x_initial_dev,sd_logProd_initial_dev,import_share_initial_dev,worker_bond_holding_initial_dev,
domestic_bond_holding_initial_dev,exporter_bond_holding_initial_dev,domestic_firm_debt_initial_dev,
exporter_firm_debt_initial_dev,avg_Pi_x_initial_dev,avg_Pi_d_initial_dev,Profit_fine_x_initial_dev,
Profit_fine_d_initial_dev,mean_cons_initial_dev,sd_cons_initial_dev,mean_income_initial_dev,sd_income_initial_dev,mean_wealth_initial_dev,
sd_wealth_initial_dev,wealth_of_workers_initial_dev,wealth_of_domestic_initial_dev,wealth_of_exporters_initial_dev,
income_of_workers_initial_dev,income_of_domestic_initial_dev,income_of_exporters_initial_dev,
cons_of_workers_initial_dev,cons_of_domestic_initial_dev,cons_of_exporters_initial_dev,GINI_wealth_initial_dev,
GINI_income_initial_dev,GINI_cons_initial_dev,p10_wealth_initial_dev,p50_wealth_initial_dev,p90_wealth_initial_dev,p99_wealth_initial_dev,p10_income_initial_dev,p50_income_initial_dev,p90_income_initial_dev,
p99_income_initial_dev,p10_cons_initial_dev,p50_cons_initial_dev,p90_cons_initial_dev,p99_cons_initial_dev,Aggr_bank_cost_initial_dev,mean_leverage_d_initial_dev,mean_leverage_x_initial_dev,mean_leverage_initial_dev,
sd_leverage_d_initial_dev,sd_leverage_x_initial_dev,sd_leverage_initial_dev,corr_MRPK_lev_d_initial_dev,corr_MRPK_lev_x_initial_dev,corr_MRPK_lev_initial_dev,exit_domestic_to_work_sum_initial_dev,
exit_exporting_to_work_sum_initial_dev,mean_growth_rev_initial_dev,sd_growth_rev_initial_dev,mean_growth_k_initial_dev,sd_growth_k_initial_dev,autocorr_rev_initial_dev,
fraction_zombie_exporter_initial_dev,Misallocation_within_d_initial_dev,Misallocation_within_x_initial_dev,k_opt_d_fine_initial_dev,k_opt_x_fine_initial_dev) = Residual_stst_detailed(prices_initial_dev, Developed_parameter);

#Closed capital markets and after trade liberalization
closed_CM_open_trade_dev_parameter = copy(Developed_parameter);
τ_open_trade = 0.354; #Final bilateral low tariff state
closed_CM_open_trade_dev_parameter.τ = τ_open_trade * [1.0,1.0];

prices_closed_CM_open_trade_dev = [    0.2490842781272958,
 0.3799239726656807,
 0.23192180425628187,
 2.16046684198267,
 1.2704952921209134,
 0.05638316639491758,
 0.0512674722023119];

(residual_closed_CM_open_trade_dev,a_prime_fine_closed_CM_open_trade_dev,future_occupation_fine_closed_CM_open_trade_dev,cons_fine_closed_CM_open_trade_dev,rev_d_fine_store_closed_CM_open_trade_dev,
rev_dx_fine_store_closed_CM_open_trade_dev,rev_xx_fine_store_closed_CM_open_trade_dev,coeff_final_closed_CM_open_trade_dev,k_x_fine_closed_CM_open_trade_dev,k_d_fine_closed_CM_open_trade_dev,
l_x_fine_closed_CM_open_trade_dev,l_d_fine_closed_CM_open_trade_dev,current_distr_store_closed_CM_open_trade_dev,distr_current_closed_CM_open_trade_dev,exitflag_closed_CM_open_trade_dev,domestic_prod_closed_CM_open_trade_dev,exporter_pop_closed_CM_open_trade_dev,
domestic_pop_closed_CM_open_trade_dev,worker_pop_closed_CM_open_trade_dev,entry_share_to_domestic_closed_CM_open_trade_dev,exit_share_to_domestic_closed_CM_open_trade_dev,
entry_share_to_exporter_closed_CM_open_trade_dev,exit_share_to_worker_closed_CM_open_trade_dev,total_entry_cost_closed_CM_open_trade_dev,
total_incumbents_cost_closed_CM_open_trade_dev,total_exit_cost_closed_CM_open_trade_dev,labor_excess_demand_closed_CM_open_trade_dev,labor_demand_closed_CM_open_trade_dev,
total_consumption_closed_CM_open_trade_dev,capital_demand_closed_CM_open_trade_dev,capital_next_closed_CM_open_trade_dev,
total_demand_final_good_closed_CM_open_trade_dev,excess_demand_final_good_closed_CM_open_trade_dev,GDP_closed_CM_open_trade_dev,nomGDP_closed_CM_open_trade_dev,PPI_closed_CM_open_trade_dev,TFP_closed_CM_open_trade_dev,
TFP_within_closed_CM_open_trade_dev,TFP_across_closed_CM_open_trade_dev,TFP_second_best_closed_CM_open_trade_dev,TOT_closed_CM_open_trade_dev,TFP_d_closed_CM_open_trade_dev,
TFP_d_efficient_closed_CM_open_trade_dev,TFP_x_closed_CM_open_trade_dev,TFP_x_efficient_closed_CM_open_trade_dev,total_production_closed_CM_open_trade_dev,
domestic_price_sum_closed_CM_open_trade_dev,export_value_closed_CM_open_trade_dev,investment_closed_CM_open_trade_dev,
export_value_closed_CM_open_trade_dev,L_x_closed_CM_open_trade_dev,L_d_closed_CM_open_trade_dev,K_x_closed_CM_open_trade_dev,K_d_closed_CM_open_trade_dev,x_k_closed_CM_open_trade_dev,x_l_closed_CM_open_trade_dev,D_d_closed_CM_open_trade_dev,D_x_closed_CM_open_trade_dev,D_d_denom_closed_CM_open_trade_dev,D_x_denom_closed_CM_open_trade_dev,
D_d_eff_closed_CM_open_trade_dev,D_x_eff_closed_CM_open_trade_dev,D_d_denom_eff_closed_CM_open_trade_dev,D_x_denom_eff_closed_CM_open_trade_dev,K_d_ratio_closed_CM_open_trade_dev,K_x_ratio_closed_CM_open_trade_dev,
L_d_ratio_closed_CM_open_trade_dev,L_x_ratio_closed_CM_open_trade_dev,K_x_ratio_eff_closed_CM_open_trade_dev,K_d_ratio_eff_closed_CM_open_trade_dev,L_d_ratio_eff_closed_CM_open_trade_dev,
L_x_ratio_eff_closed_CM_open_trade_dev,nomGDP_d_closed_CM_open_trade_dev,nomGDP_xd_closed_CM_open_trade_dev,nomGDP_xx_closed_CM_open_trade_dev,RGDP_d_closed_CM_open_trade_dev,RGDP_xd_closed_CM_open_trade_dev,RGDP_xx_closed_CM_open_trade_dev,RGDP_closed_CM_open_trade_dev,
mean_MRPK_d_closed_CM_open_trade_dev,mean_MRPK_x_closed_CM_open_trade_dev,sd_MRPK_d_closed_CM_open_trade_dev,sd_MRPK_x_closed_CM_open_trade_dev,mean_MRPK_closed_CM_open_trade_dev,sd_MRPK_closed_CM_open_trade_dev,
mean_MRPL_d_closed_CM_open_trade_dev,mean_MRPL_x_closed_CM_open_trade_dev,sd_MRPL_d_closed_CM_open_trade_dev,sd_MRPL_x_closed_CM_open_trade_dev,mean_MRPL_closed_CM_open_trade_dev,sd_MRPL_closed_CM_open_trade_dev,
cov_TFPR_z_d_closed_CM_open_trade_dev,cov_TFPR_z_x_closed_CM_open_trade_dev,cov_TFPR_z_closed_CM_open_trade_dev,corr_TFPR_z_d_closed_CM_open_trade_dev,corr_TFPR_z_x_closed_CM_open_trade_dev,
corr_TFPR_z_closed_CM_open_trade_dev,mean_logProd_d_closed_CM_open_trade_dev,mean_logProd_x_closed_CM_open_trade_dev,mean_logProd_closed_CM_open_trade_dev,sd_logProd_d_closed_CM_open_trade_dev,
sd_logProd_x_closed_CM_open_trade_dev,sd_logProd_closed_CM_open_trade_dev,import_share_closed_CM_open_trade_dev,worker_bond_holding_closed_CM_open_trade_dev,
domestic_bond_holding_closed_CM_open_trade_dev,exporter_bond_holding_closed_CM_open_trade_dev,domestic_firm_debt_closed_CM_open_trade_dev,
exporter_firm_debt_closed_CM_open_trade_dev,avg_Pi_x_closed_CM_open_trade_dev,avg_Pi_d_closed_CM_open_trade_dev,Profit_fine_x_closed_CM_open_trade_dev,
Profit_fine_d_closed_CM_open_trade_dev,mean_cons_closed_CM_open_trade_dev,sd_cons_closed_CM_open_trade_dev,mean_income_closed_CM_open_trade_dev,sd_income_closed_CM_open_trade_dev,mean_wealth_closed_CM_open_trade_dev,
sd_wealth_closed_CM_open_trade_dev,wealth_of_workers_closed_CM_open_trade_dev,wealth_of_domestic_closed_CM_open_trade_dev,wealth_of_exporters_closed_CM_open_trade_dev,
income_of_workers_closed_CM_open_trade_dev,income_of_domestic_closed_CM_open_trade_dev,income_of_exporters_closed_CM_open_trade_dev,
cons_of_workers_closed_CM_open_trade_dev,cons_of_domestic_closed_CM_open_trade_dev,cons_of_exporters_closed_CM_open_trade_dev,GINI_wealth_closed_CM_open_trade_dev,
GINI_income_closed_CM_open_trade_dev,GINI_cons_closed_CM_open_trade_dev,p10_wealth_closed_CM_open_trade_dev,p50_wealth_closed_CM_open_trade_dev,p90_wealth_closed_CM_open_trade_dev,p99_wealth_closed_CM_open_trade_dev,p10_income_closed_CM_open_trade_dev,p50_income_closed_CM_open_trade_dev,p90_income_closed_CM_open_trade_dev,
p99_income_closed_CM_open_trade_dev,p10_cons_closed_CM_open_trade_dev,p50_cons_closed_CM_open_trade_dev,p90_cons_closed_CM_open_trade_dev,p99_cons_closed_CM_open_trade_dev,Aggr_bank_cost_closed_CM_open_trade_dev,mean_leverage_d_closed_CM_open_trade_dev,mean_leverage_x_closed_CM_open_trade_dev,mean_leverage_closed_CM_open_trade_dev,
sd_leverage_d_closed_CM_open_trade_dev,sd_leverage_x_closed_CM_open_trade_dev,sd_leverage_closed_CM_open_trade_dev,corr_MRPK_lev_d_closed_CM_open_trade_dev,corr_MRPK_lev_x_closed_CM_open_trade_dev,corr_MRPK_lev_closed_CM_open_trade_dev,exit_domestic_to_work_sum_closed_CM_open_trade_dev,
exit_exporting_to_work_sum_closed_CM_open_trade_dev,mean_growth_rev_closed_CM_open_trade_dev,sd_growth_rev_closed_CM_open_trade_dev,mean_growth_k_closed_CM_open_trade_dev,sd_growth_k_closed_CM_open_trade_dev,autocorr_rev_closed_CM_open_trade_dev,fraction_zombie_exporter_closed_CM_open_trade_dev,
Misallocation_within_d_closed_CM_open_trade_dev,Misallocation_within_x_closed_CM_open_trade_dev,k_opt_d_fine_closed_CM_open_trade_dev,k_opt_x_fine_closed_CM_open_trade_dev) = Residual_stst_detailed(prices_closed_CM_open_trade_dev, closed_CM_open_trade_dev_parameter);

#Open capital markets and after trade liberalization
open_CM_open_trade_dev_parameter = copy(Developed_parameter);
open_CM_open_trade_dev_parameter.openness = 1;

τ_open_trade = 0.354; #Final bilateral low tariff state
open_CM_open_trade_dev_parameter.τ = τ_open_trade * [1.0,1.0];
prices_open_CM_open_trade_dev =  [    0.24106826816748464,
 0.3816586858128931,
 0.22382022147925293,
 2.178417385437627,
 1.2814473794622987,
 0.0514290052412662];

(residual_open_CM_open_trade_dev,a_prime_fine_open_CM_open_trade_dev,future_occupation_fine_open_CM_open_trade_dev,cons_fine_open_CM_open_trade_dev,rev_d_fine_store_open_CM_open_trade_dev,
rev_dx_fine_store_open_CM_open_trade_dev,rev_xx_fine_store_open_CM_open_trade_dev,coeff_final_open_CM_open_trade_dev,k_x_fine_open_CM_open_trade_dev,k_d_fine_open_CM_open_trade_dev,
l_x_fine_open_CM_open_trade_dev,l_d_fine_open_CM_open_trade_dev,current_distr_store_open_CM_open_trade_dev,distr_current_open_CM_open_trade_dev,exitflag_open_CM_open_trade_dev,domestic_prod_open_CM_open_trade_dev,exporter_pop_open_CM_open_trade_dev,
domestic_pop_open_CM_open_trade_dev,worker_pop_open_CM_open_trade_dev,entry_share_to_domestic_open_CM_open_trade_dev,exit_share_to_domestic_open_CM_open_trade_dev,
entry_share_to_exporter_open_CM_open_trade_dev,exit_share_to_worker_open_CM_open_trade_dev,total_entry_cost_open_CM_open_trade_dev,
total_incumbents_cost_open_CM_open_trade_dev,total_exit_cost_open_CM_open_trade_dev,labor_excess_demand_open_CM_open_trade_dev,labor_demand_open_CM_open_trade_dev,
total_consumption_open_CM_open_trade_dev,capital_demand_open_CM_open_trade_dev,capital_next_open_CM_open_trade_dev,
total_demand_final_good_open_CM_open_trade_dev,excess_demand_final_good_open_CM_open_trade_dev,GDP_open_CM_open_trade_dev,nomGDP_open_CM_open_trade_dev,PPI_open_CM_open_trade_dev,TFP_open_CM_open_trade_dev,
TFP_within_open_CM_open_trade_dev,TFP_across_open_CM_open_trade_dev,TFP_second_best_open_CM_open_trade_dev,TOT_open_CM_open_trade_dev,TFP_d_open_CM_open_trade_dev,
TFP_d_efficient_open_CM_open_trade_dev,TFP_x_open_CM_open_trade_dev,TFP_x_efficient_open_CM_open_trade_dev,total_production_open_CM_open_trade_dev,
domestic_price_sum_open_CM_open_trade_dev,export_value_open_CM_open_trade_dev,investment_open_CM_open_trade_dev,
export_value_open_CM_open_trade_dev,L_x_open_CM_open_trade_dev,L_d_open_CM_open_trade_dev,K_x_open_CM_open_trade_dev,K_d_open_CM_open_trade_dev,x_k_open_CM_open_trade_dev,x_l_open_CM_open_trade_dev,D_d_open_CM_open_trade_dev,D_x_open_CM_open_trade_dev,D_d_denom_open_CM_open_trade_dev,D_x_denom_open_CM_open_trade_dev,
D_d_eff_open_CM_open_trade_dev,D_x_eff_open_CM_open_trade_dev,D_d_denom_eff_open_CM_open_trade_dev,D_x_denom_eff_open_CM_open_trade_dev,K_d_ratio_open_CM_open_trade_dev,K_x_ratio_open_CM_open_trade_dev,
L_d_ratio_open_CM_open_trade_dev,L_x_ratio_open_CM_open_trade_dev,K_x_ratio_eff_open_CM_open_trade_dev,K_d_ratio_eff_open_CM_open_trade_dev,L_d_ratio_eff_open_CM_open_trade_dev,
L_x_ratio_eff_open_CM_open_trade_dev,nomGDP_d_open_CM_open_trade_dev,nomGDP_xd_open_CM_open_trade_dev,nomGDP_xx_open_CM_open_trade_dev,RGDP_d_open_CM_open_trade_dev,RGDP_xd_open_CM_open_trade_dev,RGDP_xx_open_CM_open_trade_dev,RGDP_open_CM_open_trade_dev,
mean_MRPK_d_open_CM_open_trade_dev,mean_MRPK_x_open_CM_open_trade_dev,sd_MRPK_d_open_CM_open_trade_dev,sd_MRPK_x_open_CM_open_trade_dev,mean_MRPK_open_CM_open_trade_dev,sd_MRPK_open_CM_open_trade_dev,
mean_MRPL_d_open_CM_open_trade_dev,mean_MRPL_x_open_CM_open_trade_dev,sd_MRPL_d_open_CM_open_trade_dev,sd_MRPL_x_open_CM_open_trade_dev,mean_MRPL_open_CM_open_trade_dev,sd_MRPL_open_CM_open_trade_dev,
cov_TFPR_z_d_open_CM_open_trade_dev,cov_TFPR_z_x_open_CM_open_trade_dev,cov_TFPR_z_open_CM_open_trade_dev,corr_TFPR_z_d_open_CM_open_trade_dev,corr_TFPR_z_x_open_CM_open_trade_dev,
corr_TFPR_z_open_CM_open_trade_dev,mean_logProd_d_open_CM_open_trade_dev,mean_logProd_x_open_CM_open_trade_dev,mean_logProd_open_CM_open_trade_dev,sd_logProd_d_open_CM_open_trade_dev,
sd_logProd_x_open_CM_open_trade_dev,sd_logProd_open_CM_open_trade_dev,import_share_open_CM_open_trade_dev,worker_bond_holding_open_CM_open_trade_dev,
domestic_bond_holding_open_CM_open_trade_dev,exporter_bond_holding_open_CM_open_trade_dev,domestic_firm_debt_open_CM_open_trade_dev,
exporter_firm_debt_open_CM_open_trade_dev,avg_Pi_x_open_CM_open_trade_dev,avg_Pi_d_open_CM_open_trade_dev,Profit_fine_x_open_CM_open_trade_dev,
Profit_fine_d_open_CM_open_trade_dev,mean_cons_open_CM_open_trade_dev,sd_cons_open_CM_open_trade_dev,mean_income_open_CM_open_trade_dev,sd_income_open_CM_open_trade_dev,mean_wealth_open_CM_open_trade_dev,
sd_wealth_open_CM_open_trade_dev,wealth_of_workers_open_CM_open_trade_dev,wealth_of_domestic_open_CM_open_trade_dev,wealth_of_exporters_open_CM_open_trade_dev,
income_of_workers_open_CM_open_trade_dev,income_of_domestic_open_CM_open_trade_dev,income_of_exporters_open_CM_open_trade_dev,
cons_of_workers_open_CM_open_trade_dev,cons_of_domestic_open_CM_open_trade_dev,cons_of_exporters_open_CM_open_trade_dev,GINI_wealth_open_CM_open_trade_dev,
GINI_income_open_CM_open_trade_dev,GINI_cons_open_CM_open_trade_dev,p10_wealth_open_CM_open_trade_dev,p50_wealth_open_CM_open_trade_dev,p90_wealth_open_CM_open_trade_dev,p99_wealth_open_CM_open_trade_dev,p10_income_open_CM_open_trade_dev,p50_income_open_CM_open_trade_dev,p90_income_open_CM_open_trade_dev,
p99_income_open_CM_open_trade_dev,p10_cons_open_CM_open_trade_dev,p50_cons_open_CM_open_trade_dev,p90_cons_open_CM_open_trade_dev,p99_cons_open_CM_open_trade_dev,Aggr_bank_cost_open_CM_open_trade_dev,mean_leverage_d_open_CM_open_trade_dev,mean_leverage_x_open_CM_open_trade_dev,mean_leverage_open_CM_open_trade_dev,
sd_leverage_d_open_CM_open_trade_dev,sd_leverage_x_open_CM_open_trade_dev,sd_leverage_open_CM_open_trade_dev,corr_MRPK_lev_d_open_CM_open_trade_dev,corr_MRPK_lev_x_open_CM_open_trade_dev,corr_MRPK_lev_open_CM_open_trade_dev,exit_domestic_to_work_sum_open_CM_open_trade_dev,
exit_exporting_to_work_sum_open_CM_open_trade_dev,mean_growth_rev_open_CM_open_trade_dev,sd_growth_rev_open_CM_open_trade_dev,mean_growth_k_open_CM_open_trade_dev,sd_growth_k_open_CM_open_trade_dev,autocorr_rev_open_CM_open_trade_dev,fraction_zombie_exporter_open_CM_open_trade_dev,
Misallocation_within_d_open_CM_open_trade_dev,Misallocation_within_x_open_CM_open_trade_dev,k_opt_d_fine_open_CM_open_trade_dev,k_opt_x_fine_open_CM_open_trade_dev) = Residual_stst_detailed(prices_open_CM_open_trade_dev, open_CM_open_trade_dev_parameter);

#Open capital markets but no trade liberalization
open_CM_closed_trade_dev_parameter = copy(Developed_parameter);
open_CM_closed_trade_dev_parameter.openness = 1;

τ_closed_trade = 0.525;
open_CM_closed_trade_dev_parameter.τ = τ_closed_trade * [1.0,1.0];
prices_open_CM_closed_trade_dev =  [0.23682352802411427,
 0.38112005081922895,
 0.23684346058879885,
 2.2709889030267885,
 1.2852541180790449,
 0.05012701009487472];

(residual_open_CM_closed_trade_dev,a_prime_fine_open_CM_closed_trade_dev,future_occupation_fine_open_CM_closed_trade_dev,cons_fine_open_CM_closed_trade_dev,rev_d_fine_store_open_CM_closed_trade_dev,
rev_dx_fine_store_open_CM_closed_trade_dev,rev_xx_fine_store_open_CM_closed_trade_dev,coeff_final_open_CM_closed_trade_dev,k_x_fine_open_CM_closed_trade_dev,k_d_fine_open_CM_closed_trade_dev,
l_x_fine_open_CM_closed_trade_dev,l_d_fine_open_CM_closed_trade_dev,current_distr_store_open_CM_closed_trade_dev,distr_current_open_CM_closed_trade_dev,exitflag_open_CM_closed_trade_dev,domestic_prod_open_CM_closed_trade_dev,exporter_pop_open_CM_closed_trade_dev,
domestic_pop_open_CM_closed_trade_dev,worker_pop_open_CM_closed_trade_dev,entry_share_to_domestic_open_CM_closed_trade_dev,exit_share_to_domestic_open_CM_closed_trade_dev,
entry_share_to_exporter_open_CM_closed_trade_dev,exit_share_to_worker_open_CM_closed_trade_dev,total_entry_cost_open_CM_closed_trade_dev,
total_incumbents_cost_open_CM_closed_trade_dev,total_exit_cost_open_CM_closed_trade_dev,labor_excess_demand_open_CM_closed_trade_dev,labor_demand_open_CM_closed_trade_dev,
total_consumption_open_CM_closed_trade_dev,capital_demand_open_CM_closed_trade_dev,capital_next_open_CM_closed_trade_dev,
total_demand_final_good_open_CM_closed_trade_dev,excess_demand_final_good_open_CM_closed_trade_dev,GDP_open_CM_closed_trade_dev,nomGDP_open_CM_closed_trade_dev,PPI_open_CM_closed_trade_dev,TFP_open_CM_closed_trade_dev,
TFP_within_open_CM_closed_trade_dev,TFP_across_open_CM_closed_trade_dev,TFP_second_best_open_CM_closed_trade_dev,TOT_open_CM_closed_trade_dev,TFP_d_open_CM_closed_trade_dev,
TFP_d_efficient_open_CM_closed_trade_dev,TFP_x_open_CM_closed_trade_dev,TFP_x_efficient_open_CM_closed_trade_dev,total_production_open_CM_closed_trade_dev,
domestic_price_sum_open_CM_closed_trade_dev,export_value_open_CM_closed_trade_dev,investment_open_CM_closed_trade_dev,
export_value_open_CM_closed_trade_dev,L_x_open_CM_closed_trade_dev,L_d_open_CM_closed_trade_dev,K_x_open_CM_closed_trade_dev,K_d_open_CM_closed_trade_dev,x_k_open_CM_closed_trade_dev,x_l_open_CM_closed_trade_dev,D_d_open_CM_closed_trade_dev,D_x_open_CM_closed_trade_dev,D_d_denom_open_CM_closed_trade_dev,D_x_denom_open_CM_closed_trade_dev,
D_d_eff_open_CM_closed_trade_dev,D_x_eff_open_CM_closed_trade_dev,D_d_denom_eff_open_CM_closed_trade_dev,D_x_denom_eff_open_CM_closed_trade_dev,K_d_ratio_open_CM_closed_trade_dev,K_x_ratio_open_CM_closed_trade_dev,
L_d_ratio_open_CM_closed_trade_dev,L_x_ratio_open_CM_closed_trade_dev,K_x_ratio_eff_open_CM_closed_trade_dev,K_d_ratio_eff_open_CM_closed_trade_dev,L_d_ratio_eff_open_CM_closed_trade_dev,
L_x_ratio_eff_open_CM_closed_trade_dev,nomGDP_d_open_CM_closed_trade_dev,nomGDP_xd_open_CM_closed_trade_dev,nomGDP_xx_open_CM_closed_trade_dev,RGDP_d_open_CM_closed_trade_dev,RGDP_xd_open_CM_closed_trade_dev,RGDP_xx_open_CM_closed_trade_dev,RGDP_open_CM_closed_trade_dev,
mean_MRPK_d_open_CM_closed_trade_dev,mean_MRPK_x_open_CM_closed_trade_dev,sd_MRPK_d_open_CM_closed_trade_dev,sd_MRPK_x_open_CM_closed_trade_dev,mean_MRPK_open_CM_closed_trade_dev,sd_MRPK_open_CM_closed_trade_dev,
mean_MRPL_d_open_CM_closed_trade_dev,mean_MRPL_x_open_CM_closed_trade_dev,sd_MRPL_d_open_CM_closed_trade_dev,sd_MRPL_x_open_CM_closed_trade_dev,mean_MRPL_open_CM_closed_trade_dev,sd_MRPL_open_CM_closed_trade_dev,
cov_TFPR_z_d_open_CM_closed_trade_dev,cov_TFPR_z_x_open_CM_closed_trade_dev,cov_TFPR_z_open_CM_closed_trade_dev,corr_TFPR_z_d_open_CM_closed_trade_dev,corr_TFPR_z_x_open_CM_closed_trade_dev,
corr_TFPR_z_open_CM_closed_trade_dev,mean_logProd_d_open_CM_closed_trade_dev,mean_logProd_x_open_CM_closed_trade_dev,mean_logProd_open_CM_closed_trade_dev,sd_logProd_d_open_CM_closed_trade_dev,
sd_logProd_x_open_CM_closed_trade_dev,sd_logProd_open_CM_closed_trade_dev,import_share_open_CM_closed_trade_dev,worker_bond_holding_open_CM_closed_trade_dev,
domestic_bond_holding_open_CM_closed_trade_dev,exporter_bond_holding_open_CM_closed_trade_dev,domestic_firm_debt_open_CM_closed_trade_dev,
exporter_firm_debt_open_CM_closed_trade_dev,avg_Pi_x_open_CM_closed_trade_dev,avg_Pi_d_open_CM_closed_trade_dev,Profit_fine_x_open_CM_closed_trade_dev,
Profit_fine_d_open_CM_closed_trade_dev,mean_cons_open_CM_closed_trade_dev,sd_cons_open_CM_closed_trade_dev,mean_income_open_CM_closed_trade_dev,sd_income_open_CM_closed_trade_dev,mean_wealth_open_CM_closed_trade_dev,
sd_wealth_open_CM_closed_trade_dev,wealth_of_workers_open_CM_closed_trade_dev,wealth_of_domestic_open_CM_closed_trade_dev,wealth_of_exporters_open_CM_closed_trade_dev,
income_of_workers_open_CM_closed_trade_dev,income_of_domestic_open_CM_closed_trade_dev,income_of_exporters_open_CM_closed_trade_dev,
cons_of_workers_open_CM_closed_trade_dev,cons_of_domestic_open_CM_closed_trade_dev,cons_of_exporters_open_CM_closed_trade_dev,GINI_wealth_open_CM_closed_trade_dev,
GINI_income_open_CM_closed_trade_dev,GINI_cons_open_CM_closed_trade_dev,p10_wealth_open_CM_closed_trade_dev,p50_wealth_open_CM_closed_trade_dev,p90_wealth_open_CM_closed_trade_dev,p99_wealth_open_CM_closed_trade_dev,p10_income_open_CM_closed_trade_dev,p50_income_open_CM_closed_trade_dev,p90_income_open_CM_closed_trade_dev,
p99_income_open_CM_closed_trade_dev,p10_cons_open_CM_closed_trade_dev,p50_cons_open_CM_closed_trade_dev,p90_cons_open_CM_closed_trade_dev,p99_cons_open_CM_closed_trade_dev,Aggr_bank_cost_open_CM_closed_trade_dev,mean_leverage_d_open_CM_closed_trade_dev,mean_leverage_x_open_CM_closed_trade_dev,mean_leverage_open_CM_closed_trade_dev,
sd_leverage_d_open_CM_closed_trade_dev,sd_leverage_x_open_CM_closed_trade_dev,sd_leverage_open_CM_closed_trade_dev,corr_MRPK_lev_d_open_CM_closed_trade_dev,corr_MRPK_lev_x_open_CM_closed_trade_dev,corr_MRPK_lev_open_CM_closed_trade_dev,exit_domestic_to_work_sum_open_CM_closed_trade_dev,
exit_exporting_to_work_sum_open_CM_closed_trade_dev,mean_growth_rev_open_CM_closed_trade_dev,sd_growth_rev_open_CM_closed_trade_dev,mean_growth_k_open_CM_closed_trade_dev,sd_growth_k_open_CM_closed_trade_dev,autocorr_rev_open_CM_closed_trade_dev,fraction_zombie_exporter_open_CM_closed_trade_dev,
Misallocation_within_d_open_CM_closed_trade_dev,Misallocation_within_x_open_CM_closed_trade_dev,k_opt_d_fine_open_CM_closed_trade_dev,k_opt_x_fine_open_CM_closed_trade_dev) = Residual_stst_detailed(prices_open_CM_closed_trade_dev, open_CM_closed_trade_dev_parameter);

#end
